/**
 * Communication feature flag identifiers (Phase 7).
 * Env vars use the NEXT_PUBLIC_COMMUNICATION_* prefix (or NEXT_PUBLIC_EMAIL_AI_* for executive enhancements).
 * Production: Email Automation / Workspace / AI default ON; Voice AI + WhatsApp UI default OFF (hidden).
 * EMAIL_AI_* executive flags default OFF unless noted.
 */
export const COMMUNICATION_FEATURE_FLAG_IDS = [
  "COMMUNICATION_ENTERPRISE_FOUNDATION",
  "COMMUNICATION_VOICE_AI",
  "COMMUNICATION_VOICE_ASSISTANT",
  "COMMUNICATION_VOICE_COMMANDS",
  "COMMUNICATION_SPEECH_TO_TEXT",
  "COMMUNICATION_TEXT_TO_SPEECH",
  "COMMUNICATION_WHATSAPP_INTEGRATION",
  "COMMUNICATION_WHATSAPP_MESSAGING",
  "COMMUNICATION_EMAIL_AUTOMATION",
  "COMMUNICATION_EMAIL_TEMPLATES",
  "COMMUNICATION_AI_ASSISTANT",
  /** Phase 2 brief aliases / capabilities */
  "COMMUNICATION_SPEECH_UI",
  "COMMUNICATION_VOICE_ACTIONS",
  "COMMUNICATION_WHATSAPP",
  "COMMUNICATION_WHATSAPP_QUEUE",
  "COMMUNICATION_ORCHESTRATION",
  "COMMUNICATION_STATUS",
  "COMMUNICATION_FEEDBACK",
  /** Task 7.3 — Enterprise AI Email Workspace (default OFF) */
  "COMMUNICATION_EMAIL_WORKSPACE",
  "COMMUNICATION_EMAIL_AI",
  "COMMUNICATION_EMAIL_THREADS",
  "COMMUNICATION_EMAIL_VOICE",
  "COMMUNICATION_EMAIL_SEARCH",
  "COMMUNICATION_EMAIL_SHARED_INBOX",
  "COMMUNICATION_EMAIL_SMART_REPLY",
  "COMMUNICATION_EMAIL_SCHEDULE",
  "COMMUNICATION_EMAIL_ENTERPRISE_UI",
  /** Executive Assistant enhancements (default OFF — independent rollback) */
  "EMAIL_AI_CONTACT_RESOLUTION",
  "EMAIL_AI_SMART_PREVIEW",
  "EMAIL_AI_SMART_VALIDATION",
  "EMAIL_AI_REWRITE",
  "EMAIL_AI_SCHEDULE",
  "EMAIL_AI_INSIGHTS",
  "EMAIL_AI_THREADS",
  "EMAIL_AI_SEARCH",
  "EMAIL_AI_VOICE",
  "EMAIL_AI_GROUPS",
  "EMAIL_AI_EXECUTIVE_UI",
  "EMAIL_AI_COMMAND_PALETTE",
] as const;

export type CommunicationFeatureFlagId =
  (typeof COMMUNICATION_FEATURE_FLAG_IDS)[number];

/** Snapshot of all communication flags. */
export type CommunicationFeatureFlags = Readonly<
  Record<CommunicationFeatureFlagId, boolean>
>;
