export type {
  CommunicationFeatureFlagId,
  CommunicationFeatureFlags,
} from "./communication-feature-flag.types";
export { COMMUNICATION_FEATURE_FLAG_IDS } from "./communication-feature-flag.types";
export {
  getCommunicationFeatureFlags,
  getEmailAiExecutiveFlags,
  isCommunicationAiAssistantEnabled,
  isCommunicationEmailAiEnabled,
  isCommunicationEmailAutomationEnabled,
  isCommunicationEmailEnterpriseUiEnabled,
  isCommunicationEmailPresentationEnabled,
  isCommunicationEmailScheduleEnabled,
  isCommunicationEmailSearchEnabled,
  isCommunicationEmailSharedInboxEnabled,
  isCommunicationEmailSmartReplyEnabled,
  isCommunicationEmailTemplatesEnabled,
  isCommunicationEmailThreadsEnabled,
  isCommunicationEmailVoiceEnabled,
  isCommunicationEmailWorkspaceEnabled,
  isCommunicationEmailWorkspacePresentationEnabled,
  isCommunicationEnterpriseFoundationEnabled,
  isCommunicationFeatureEnabled,
  isCommunicationFeedbackEnabled,
  isCommunicationOrchestrationEnabled,
  isCommunicationSpeechToTextEnabled,
  isCommunicationSpeechUiEnabled,
  isCommunicationStatusEnabled,
  isCommunicationTextToSpeechEnabled,
  isCommunicationVoiceActionsEnabled,
  isCommunicationVoiceAiEnabled,
  isCommunicationVoiceAiPageEnabled,
  isCommunicationVoiceAssistantEnabled,
  isCommunicationVoiceCommandsEnabled,
  isCommunicationVoicePresentationEnabled,
  isCommunicationWhatsappEnabled,
  isCommunicationWhatsappIntegrationEnabled,
  isCommunicationWhatsappMessagingEnabled,
  isCommunicationWhatsappPageEnabled,
  isCommunicationWhatsappPresentationEnabled,
  isCommunicationWhatsappQueueEnabled,
  isEmailAiCommandPaletteEnabled,
  isEmailAiContactResolutionEnabled,
  isEmailAiExecutiveAnyEnabled,
  isEmailAiExecutiveUiEnabled,
  isEmailAiGroupsEnabled,
  isEmailAiInsightsEnabled,
  isEmailAiRewriteEnabled,
  isEmailAiScheduleEnabled,
  isEmailAiSearchEnabled,
  isEmailAiSmartPreviewEnabled,
  isEmailAiSmartValidationEnabled,
  isEmailAiThreadsEnabled,
  isEmailAiVoiceEnabled,
} from "./communication-feature-flags";
export type { EmailAiExecutiveFlags } from "./email-ai-executive-flags";
