import type {
  SecurityEventCategory,
  SecuritySeverity,
} from "@enterprise/database";

/** Detection rule identifiers (Step 10). */
export const THREAT_DETECTION_TYPES = {
  REPEATED_FAILED_LOGIN: "REPEATED_FAILED_LOGIN",
  REPEATED_MFA_FAILURE: "REPEATED_MFA_FAILURE",
  PRIVILEGE_ESCALATION: "PRIVILEGE_ESCALATION",
  RBAC_DENIAL_SPIKE: "RBAC_DENIAL_SPIKE",
  ACL_DENIAL_SPIKE: "ACL_DENIAL_SPIKE",
  AI_POLICY_DENIAL_SPIKE: "AI_POLICY_DENIAL_SPIKE",
  AUDIT_CHAIN_CORRUPTION: "AUDIT_CHAIN_CORRUPTION",
  UPLOAD_MALWARE: "UPLOAD_MALWARE",
  UPLOAD_VALIDATION_FAILURES: "UPLOAD_VALIDATION_FAILURES",
  RATE_LIMIT_ABUSE: "RATE_LIMIT_ABUSE",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  RATE_LIMIT_BYPASSED: "RATE_LIMIT_BYPASSED",
  REDIS_UNAVAILABLE: "REDIS_UNAVAILABLE",
  CSRF_INVALID: "CSRF_INVALID",
  CSRF_EXPIRED: "CSRF_EXPIRED",
  CSRF_MISSING: "CSRF_MISSING",
  CSRF_REPLAY: "CSRF_REPLAY",
  CSRF_SESSION_MISMATCH: "CSRF_SESSION_MISMATCH",
  SESSION_ANOMALY: "SESSION_ANOMALY",
  SESSION_DEVICE_CHANGED: "SESSION_DEVICE_CHANGED",
  SESSION_IP_CHANGED: "SESSION_IP_CHANGED",
  SESSION_RISK_HIGH: "SESSION_RISK_HIGH",
  SESSION_ROTATED: "SESSION_ROTATED",
  SESSION_LIMIT_EXCEEDED: "SESSION_LIMIT_EXCEEDED",
  TRUSTED_DEVICE_USED: "TRUSTED_DEVICE_USED",
  PROMPT_INJECTION_ATTEMPT: "PROMPT_INJECTION_ATTEMPT",
  SYSTEM_PROMPT_ATTACK: "SYSTEM_PROMPT_ATTACK",
  SECRET_EXTRACTION_ATTEMPT: "SECRET_EXTRACTION_ATTEMPT",
  MEMORY_POISONING: "MEMORY_POISONING",
  DOCUMENT_INJECTION: "DOCUMENT_INJECTION",
  TOOL_INJECTION: "TOOL_INJECTION",
  OUTPUT_SECRET_LEAK: "OUTPUT_SECRET_LEAK",
  CONFIRMATION_CREATED: "CONFIRMATION_CREATED",
  CONFIRMATION_APPROVED: "CONFIRMATION_APPROVED",
  CONFIRMATION_REJECTED: "CONFIRMATION_REJECTED",
  CONFIRMATION_EXPIRED: "CONFIRMATION_EXPIRED",
  CONFIRMATION_REPLAY: "CONFIRMATION_REPLAY",
  CONFIRMATION_ARGUMENT_CHANGED: "CONFIRMATION_ARGUMENT_CHANGED",
  AI_BUDGET_WARNING: "AI_BUDGET_WARNING",
  AI_BUDGET_SOFT_LIMIT: "AI_BUDGET_SOFT_LIMIT",
  AI_BUDGET_EXCEEDED: "AI_BUDGET_EXCEEDED",
  AI_BUDGET_BLOCKED: "AI_BUDGET_BLOCKED",
  AI_COST_ANOMALY: "AI_COST_ANOMALY",
  IMPOSSIBLE_TRAVEL: "IMPOSSIBLE_TRAVEL",
  MASS_DELETE: "MASS_DELETE",
  MASS_EXPORT: "MASS_EXPORT",
  EXCESSIVE_API_ERRORS: "EXCESSIVE_API_ERRORS",
  SOD_VIOLATION_SPIKE: "SOD_VIOLATION_SPIKE",
  SECURITY_HEADERS_DISABLED: "SECURITY_HEADERS_DISABLED",
  /** Enterprise Device Management */
  DEVICE_REGISTERED: "DEVICE_REGISTERED",
  DEVICE_TRUSTED: "DEVICE_TRUSTED",
  DEVICE_REMOVED: "DEVICE_REMOVED",
  DEVICE_BLOCKED: "DEVICE_BLOCKED",
  DEVICE_REVOKED: "DEVICE_REVOKED",
  DEVICE_SUSPICIOUS: "DEVICE_SUSPICIOUS",
  UNKNOWN_DEVICE: "UNKNOWN_DEVICE",
  DEVICE_LIMIT_EXCEEDED: "DEVICE_LIMIT_EXCEEDED",
  DEVICE_POLICY_VIOLATION: "DEVICE_POLICY_VIOLATION",
  /** Enterprise Tenant Isolation Testing */
  TENANT_ISOLATION_STARTED: "TENANT_ISOLATION_STARTED",
  TENANT_ISOLATION_COMPLETED: "TENANT_ISOLATION_COMPLETED",
  TENANT_CONTEXT_MISSING: "TENANT_CONTEXT_MISSING",
  CROSS_TENANT_ACCESS: "CROSS_TENANT_ACCESS",
  CACHE_ISOLATION_FAILED: "CACHE_ISOLATION_FAILED",
  SESSION_ISOLATION_FAILED: "SESSION_ISOLATION_FAILED",
  AI_ISOLATION_FAILED: "AI_ISOLATION_FAILED",
  FILE_ISOLATION_FAILED: "FILE_ISOLATION_FAILED",
  /** Enterprise Security Regression Testing */
  SECURITY_REGRESSION_STARTED: "SECURITY_REGRESSION_STARTED",
  SECURITY_REGRESSION_COMPLETED: "SECURITY_REGRESSION_COMPLETED",
  SECURITY_REGRESSION_FAILED: "SECURITY_REGRESSION_FAILED",
  SECURITY_CONTROL_FAILED: "SECURITY_CONTROL_FAILED",
  DEPLOYMENT_NOT_READY: "DEPLOYMENT_NOT_READY",
  /** Enterprise API Versioning */
  API_VERSION_USED: "API_VERSION_USED",
  DEPRECATED_API_VERSION: "DEPRECATED_API_VERSION",
  UNSUPPORTED_API_VERSION: "UNSUPPORTED_API_VERSION",
  API_VERSION_FALLBACK: "API_VERSION_FALLBACK",
  API_VERSION_COMPATIBILITY: "API_VERSION_COMPATIBILITY",
  /** Enterprise Signed Webhooks */
  WEBHOOK_CREATED: "WEBHOOK_CREATED",
  WEBHOOK_SIGNED: "WEBHOOK_SIGNED",
  WEBHOOK_DELIVERED: "WEBHOOK_DELIVERED",
  WEBHOOK_FAILED: "WEBHOOK_FAILED",
  WEBHOOK_RETRY: "WEBHOOK_RETRY",
  WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",
  WEBHOOK_REPLAY_ATTACK: "WEBHOOK_REPLAY_ATTACK",
  WEBHOOK_SECRET_ROTATED: "WEBHOOK_SECRET_ROTATED",
  WEBHOOK_DEAD_LETTER: "WEBHOOK_DEAD_LETTER",
} as const;

export type ThreatDetectionType =
  (typeof THREAT_DETECTION_TYPES)[keyof typeof THREAT_DETECTION_TYPES];

export interface ThreatDetectionRule {
  type: ThreatDetectionType;
  /** Stored on SecurityEvent.eventType */
  eventType: string;
  category: SecurityEventCategory;
  /** Base severity for a single occurrence */
  baseSeverity: SecuritySeverity;
  /** Severity once threshold is met / for auto-incident */
  incidentSeverity: SecuritySeverity;
  /** Occurrences within window before incident aggregation */
  threshold: number;
  windowMs: number;
  /** Always open/update an incident on first event (CRITICAL paths) */
  immediateIncident?: boolean;
  module: string;
}

export interface ReportThreatInput {
  type: ThreatDetectionType;
  userId?: string | null;
  resource?: string | null;
  resourceId?: string | null;
  message?: string;
  metadata?: Record<string, unknown>;
  ipAddress?: string | null;
  userAgent?: string | null;
  /**
   * Optional geo for impossible-travel evaluation.
   * When absent, IMPOSSIBLE_TRAVEL is skipped (no false positives).
   */
  location?: {
    country?: string | null;
    lat?: number | null;
    lon?: number | null;
  } | null;
}

export interface ThreatReportResult {
  eventId: string | null;
  incidentId: string | null;
  incidentCreated: boolean;
  incidentUpdated: boolean;
  countInWindow: number;
  severity: SecuritySeverity;
}
