import {
  THREAT_DETECTION_TYPES,
  type ThreatDetectionRule,
  type ThreatDetectionType,
} from "./monitoring.types.js";

const MIN = 60_000;
const HOUR = 60 * MIN;

/**
 * Configurable detection rules. Thresholds / windows are centralized here.
 */
export const THREAT_DETECTION_RULES: readonly ThreatDetectionRule[] = [
  {
    type: THREAT_DETECTION_TYPES.REPEATED_FAILED_LOGIN,
    eventType: "failed_login",
    category: "AUTH",
    baseSeverity: "LOW",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 15 * MIN,
    module: "auth",
  },
  {
    type: THREAT_DETECTION_TYPES.REPEATED_MFA_FAILURE,
    eventType: "mfa_failure",
    category: "AUTH",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 15 * MIN,
    module: "auth",
  },
  {
    type: THREAT_DETECTION_TYPES.PRIVILEGE_ESCALATION,
    eventType: "privilege_escalation_attempt",
    category: "ACCESS",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "authz",
  },
  {
    type: THREAT_DETECTION_TYPES.RBAC_DENIAL_SPIKE,
    eventType: "rbac_denial",
    category: "ACCESS",
    baseSeverity: "LOW",
    incidentSeverity: "HIGH",
    threshold: 10,
    windowMs: 10 * MIN,
    module: "authz",
  },
  {
    type: THREAT_DETECTION_TYPES.ACL_DENIAL_SPIKE,
    eventType: "acl_denial",
    category: "FILE",
    baseSeverity: "LOW",
    incidentSeverity: "HIGH",
    threshold: 10,
    windowMs: 10 * MIN,
    module: "files",
  },
  {
    type: THREAT_DETECTION_TYPES.AI_POLICY_DENIAL_SPIKE,
    eventType: "ai_policy_denial",
    category: "POLICY",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 8,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.AI_BUDGET_WARNING,
    eventType: "ai_budget_warning",
    category: "POLICY",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 20,
    windowMs: HOUR,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.AI_BUDGET_SOFT_LIMIT,
    eventType: "ai_budget_soft_limit",
    category: "POLICY",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 10,
    windowMs: HOUR,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.AI_BUDGET_EXCEEDED,
    eventType: "ai_budget_exceeded",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: HOUR,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.AI_BUDGET_BLOCKED,
    eventType: "ai_budget_blocked",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.AI_COST_ANOMALY,
    eventType: "ai_cost_anomaly",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: HOUR,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.AUDIT_CHAIN_CORRUPTION,
    eventType: "AUDIT_CHAIN_CORRUPTED",
    category: "POLICY",
    baseSeverity: "CRITICAL",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 24 * HOUR,
    immediateIncident: true,
    module: "audit",
  },
  {
    type: THREAT_DETECTION_TYPES.UPLOAD_MALWARE,
    eventType: "upload_malware",
    category: "FILE",
    baseSeverity: "CRITICAL",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: HOUR,
    immediateIncident: true,
    module: "files",
  },
  {
    type: THREAT_DETECTION_TYPES.UPLOAD_VALIDATION_FAILURES,
    eventType: "upload_validation_failure",
    category: "FILE",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 8,
    windowMs: 15 * MIN,
    module: "files",
  },
  {
    type: THREAT_DETECTION_TYPES.RATE_LIMIT_ABUSE,
    eventType: "rate_limited",
    category: "RATE_LIMIT",
    baseSeverity: "LOW",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 10 * MIN,
    module: "api",
  },
  {
    type: THREAT_DETECTION_TYPES.RATE_LIMIT_EXCEEDED,
    /** Same eventType as RATE_LIMIT_ABUSE — shared aggregation stream. */
    eventType: "rate_limited",
    category: "RATE_LIMIT",
    baseSeverity: "LOW",
    incidentSeverity: "HIGH",
    /** Reuse abuse aggregation (5 / 10 min) — avoid per-hit incidents. */
    threshold: 5,
    windowMs: 10 * MIN,
    module: "api",
  },
  {
    type: THREAT_DETECTION_TYPES.RATE_LIMIT_BYPASSED,
    eventType: "rate_limit_bypassed",
    category: "RATE_LIMIT",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 10 * MIN,
    module: "api",
  },
  {
    type: THREAT_DETECTION_TYPES.REDIS_UNAVAILABLE,
    eventType: "redis_unavailable",
    category: "RATE_LIMIT",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "api",
  },
  {
    type: THREAT_DETECTION_TYPES.CSRF_INVALID,
    eventType: "csrf_invalid",
    category: "ACCESS",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 10 * MIN,
    module: "csrf",
  },
  {
    type: THREAT_DETECTION_TYPES.CSRF_EXPIRED,
    eventType: "csrf_expired",
    category: "ACCESS",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 10,
    windowMs: 10 * MIN,
    module: "csrf",
  },
  {
    type: THREAT_DETECTION_TYPES.CSRF_MISSING,
    eventType: "csrf_missing",
    category: "ACCESS",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 10 * MIN,
    module: "csrf",
  },
  {
    type: THREAT_DETECTION_TYPES.CSRF_REPLAY,
    eventType: "csrf_replay",
    category: "ACCESS",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 10 * MIN,
    module: "csrf",
  },
  {
    type: THREAT_DETECTION_TYPES.CSRF_SESSION_MISMATCH,
    eventType: "csrf_session_mismatch",
    category: "ACCESS",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 10 * MIN,
    module: "csrf",
  },
  {
    type: THREAT_DETECTION_TYPES.SESSION_ANOMALY,
    eventType: "session_anomaly",
    category: "SESSION",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "auth",
  },
  {
    type: THREAT_DETECTION_TYPES.SESSION_DEVICE_CHANGED,
    eventType: "session_device_changed",
    category: "SESSION",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "session_hardening",
  },
  {
    type: THREAT_DETECTION_TYPES.SESSION_IP_CHANGED,
    eventType: "session_ip_changed",
    category: "SESSION",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 5,
    windowMs: 30 * MIN,
    module: "session_hardening",
  },
  {
    type: THREAT_DETECTION_TYPES.SESSION_RISK_HIGH,
    eventType: "session_risk_high",
    category: "SESSION",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "session_hardening",
  },
  {
    type: THREAT_DETECTION_TYPES.SESSION_ROTATED,
    eventType: "session_rotated",
    category: "SESSION",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 10,
    windowMs: 60 * MIN,
    module: "session_hardening",
  },
  {
    type: THREAT_DETECTION_TYPES.SESSION_LIMIT_EXCEEDED,
    eventType: "session_limit_exceeded",
    category: "SESSION",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "session_hardening",
  },
  {
    type: THREAT_DETECTION_TYPES.TRUSTED_DEVICE_USED,
    eventType: "trusted_device_used",
    category: "SESSION",
    baseSeverity: "LOW",
    incidentSeverity: "LOW",
    threshold: 50,
    windowMs: 60 * MIN,
    module: "session_hardening",
  },
  {
    type: THREAT_DETECTION_TYPES.PROMPT_INJECTION_ATTEMPT,
    eventType: "prompt_injection_attempt",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.SYSTEM_PROMPT_ATTACK,
    eventType: "system_prompt_attack",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 2,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.SECRET_EXTRACTION_ATTEMPT,
    eventType: "secret_extraction_attempt",
    category: "API",
    baseSeverity: "CRITICAL",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.MEMORY_POISONING,
    eventType: "memory_poisoning",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 2,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.DOCUMENT_INJECTION,
    eventType: "document_injection",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.TOOL_INJECTION,
    eventType: "tool_injection",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 2,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.CONFIRMATION_CREATED,
    eventType: "confirmation_created",
    category: "API",
    baseSeverity: "LOW",
    incidentSeverity: "LOW",
    threshold: 200,
    windowMs: 60 * MIN,
    module: "ai_confirmation",
  },
  {
    type: THREAT_DETECTION_TYPES.CONFIRMATION_APPROVED,
    eventType: "confirmation_approved",
    category: "API",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 100,
    windowMs: 60 * MIN,
    module: "ai_confirmation",
  },
  {
    type: THREAT_DETECTION_TYPES.CONFIRMATION_REJECTED,
    eventType: "confirmation_rejected",
    category: "API",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 50,
    windowMs: 60 * MIN,
    module: "ai_confirmation",
  },
  {
    type: THREAT_DETECTION_TYPES.CONFIRMATION_EXPIRED,
    eventType: "confirmation_expired",
    category: "API",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 30,
    windowMs: 60 * MIN,
    module: "ai_confirmation",
  },
  {
    type: THREAT_DETECTION_TYPES.CONFIRMATION_REPLAY,
    eventType: "confirmation_replay",
    category: "ACCESS",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 2,
    windowMs: 30 * MIN,
    module: "ai_confirmation",
  },
  {
    type: THREAT_DETECTION_TYPES.CONFIRMATION_ARGUMENT_CHANGED,
    eventType: "confirmation_argument_changed",
    category: "ACCESS",
    baseSeverity: "CRITICAL",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "ai_confirmation",
  },
  {
    type: THREAT_DETECTION_TYPES.OUTPUT_SECRET_LEAK,
    eventType: "output_secret_leak",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 2,
    windowMs: 30 * MIN,
    module: "ai",
  },
  {
    type: THREAT_DETECTION_TYPES.IMPOSSIBLE_TRAVEL,
    eventType: "impossible_travel",
    category: "SESSION",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "auth",
  },
  {
    type: THREAT_DETECTION_TYPES.MASS_DELETE,
    eventType: "mass_delete",
    category: "ACCESS",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 30 * MIN,
    immediateIncident: true,
    module: "platform",
  },
  {
    type: THREAT_DETECTION_TYPES.MASS_EXPORT,
    eventType: "mass_export",
    category: "ACCESS",
    baseSeverity: "HIGH",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "platform",
  },
  {
    type: THREAT_DETECTION_TYPES.EXCESSIVE_API_ERRORS,
    eventType: "api_error_spike",
    category: "API",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 25,
    windowMs: 5 * MIN,
    module: "api",
  },
  {
    type: THREAT_DETECTION_TYPES.SOD_VIOLATION_SPIKE,
    eventType: "sod_violation",
    category: "POLICY",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "sod",
  },
  {
    type: THREAT_DETECTION_TYPES.SECURITY_HEADERS_DISABLED,
    eventType: "security_headers_disabled",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "security_headers",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_REGISTERED,
    eventType: "device_registered",
    category: "SESSION",
    baseSeverity: "LOW",
    incidentSeverity: "LOW",
    threshold: 50,
    windowMs: 60 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_TRUSTED,
    eventType: "device_trusted",
    category: "SESSION",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 20,
    windowMs: 60 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_REMOVED,
    eventType: "device_removed",
    category: "SESSION",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 20,
    windowMs: 60 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_BLOCKED,
    eventType: "device_blocked",
    category: "SESSION",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_REVOKED,
    eventType: "device_revoked",
    category: "SESSION",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 60 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_SUSPICIOUS,
    eventType: "device_suspicious",
    category: "SESSION",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.UNKNOWN_DEVICE,
    eventType: "unknown_device",
    category: "SESSION",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 30 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_LIMIT_EXCEEDED,
    eventType: "device_limit_exceeded",
    category: "SESSION",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.DEVICE_POLICY_VIOLATION,
    eventType: "device_policy_violation",
    category: "SESSION",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 30 * MIN,
    module: "device_management",
  },
  {
    type: THREAT_DETECTION_TYPES.TENANT_ISOLATION_STARTED,
    eventType: "tenant_isolation_started",
    category: "POLICY",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 100,
    windowMs: 60 * MIN,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.TENANT_ISOLATION_COMPLETED,
    eventType: "tenant_isolation_completed",
    category: "POLICY",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 100,
    windowMs: 60 * MIN,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.TENANT_CONTEXT_MISSING,
    eventType: "tenant_context_missing",
    category: "POLICY",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 5,
    windowMs: 60 * MIN,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.CROSS_TENANT_ACCESS,
    eventType: "cross_tenant_access",
    category: "ACCESS",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.CACHE_ISOLATION_FAILED,
    eventType: "cache_isolation_failed",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.SESSION_ISOLATION_FAILED,
    eventType: "session_isolation_failed",
    category: "SESSION",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.AI_ISOLATION_FAILED,
    eventType: "ai_isolation_failed",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.FILE_ISOLATION_FAILED,
    eventType: "file_isolation_failed",
    category: "FILE",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "tenant_isolation",
  },
  {
    type: THREAT_DETECTION_TYPES.SECURITY_REGRESSION_STARTED,
    eventType: "security_regression_started",
    category: "POLICY",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 100,
    windowMs: 60 * MIN,
    module: "security_regression",
  },
  {
    type: THREAT_DETECTION_TYPES.SECURITY_REGRESSION_COMPLETED,
    eventType: "security_regression_completed",
    category: "POLICY",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 100,
    windowMs: 60 * MIN,
    module: "security_regression",
  },
  {
    type: THREAT_DETECTION_TYPES.SECURITY_REGRESSION_FAILED,
    eventType: "security_regression_failed",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "security_regression",
  },
  {
    type: THREAT_DETECTION_TYPES.SECURITY_CONTROL_FAILED,
    eventType: "security_control_failed",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 3,
    windowMs: 60 * MIN,
    module: "security_regression",
  },
  {
    type: THREAT_DETECTION_TYPES.DEPLOYMENT_NOT_READY,
    eventType: "deployment_not_ready",
    category: "POLICY",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "security_regression",
  },
  {
    type: THREAT_DETECTION_TYPES.API_VERSION_USED,
    eventType: "api_version_used",
    category: "API",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 500,
    windowMs: 60 * MIN,
    module: "api_versioning",
  },
  {
    type: THREAT_DETECTION_TYPES.DEPRECATED_API_VERSION,
    eventType: "deprecated_api_version",
    category: "API",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 20,
    windowMs: 60 * MIN,
    module: "api_versioning",
  },
  {
    type: THREAT_DETECTION_TYPES.UNSUPPORTED_API_VERSION,
    eventType: "unsupported_api_version",
    category: "API",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 10,
    windowMs: 30 * MIN,
    module: "api_versioning",
  },
  {
    type: THREAT_DETECTION_TYPES.API_VERSION_FALLBACK,
    eventType: "api_version_fallback",
    category: "API",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 50,
    windowMs: 60 * MIN,
    module: "api_versioning",
  },
  {
    type: THREAT_DETECTION_TYPES.API_VERSION_COMPATIBILITY,
    eventType: "api_version_compatibility",
    category: "API",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 100,
    windowMs: 60 * MIN,
    module: "api_versioning",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_CREATED,
    eventType: "webhook_created",
    category: "API",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 500,
    windowMs: 60 * MIN,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_SIGNED,
    eventType: "webhook_signed",
    category: "API",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 500,
    windowMs: 60 * MIN,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_DELIVERED,
    eventType: "webhook_delivered",
    category: "API",
    baseSeverity: "INFO",
    incidentSeverity: "LOW",
    threshold: 500,
    windowMs: 60 * MIN,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_FAILED,
    eventType: "webhook_failed",
    category: "API",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 20,
    windowMs: 60 * MIN,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_RETRY,
    eventType: "webhook_retry",
    category: "API",
    baseSeverity: "LOW",
    incidentSeverity: "MEDIUM",
    threshold: 50,
    windowMs: 60 * MIN,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_SIGNATURE_INVALID,
    eventType: "webhook_signature_invalid",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 5,
    windowMs: 30 * MIN,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_REPLAY_ATTACK,
    eventType: "webhook_replay_attack",
    category: "API",
    baseSeverity: "CRITICAL",
    incidentSeverity: "CRITICAL",
    threshold: 1,
    windowMs: 60 * MIN,
    immediateIncident: true,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_SECRET_ROTATED,
    eventType: "webhook_secret_rotated",
    category: "POLICY",
    baseSeverity: "MEDIUM",
    incidentSeverity: "HIGH",
    threshold: 10,
    windowMs: 24 * 60 * MIN,
    module: "webhook_security",
  },
  {
    type: THREAT_DETECTION_TYPES.WEBHOOK_DEAD_LETTER,
    eventType: "webhook_dead_letter",
    category: "API",
    baseSeverity: "HIGH",
    incidentSeverity: "CRITICAL",
    threshold: 5,
    windowMs: 60 * MIN,
    module: "webhook_security",
  },
] as const;

const RULE_BY_TYPE = new Map(
  THREAT_DETECTION_RULES.map((rule) => [rule.type, rule]),
);

export function getThreatRule(type: ThreatDetectionType): ThreatDetectionRule {
  const rule = RULE_BY_TYPE.get(type);
  if (!rule) {
    throw new Error(`Unknown threat detection type: ${type}`);
  }
  return rule;
}
