// =============================================================================
// @enterprise/shared — Barrel Exports
// =============================================================================
// Import from '@enterprise/shared' only. No deep imports.
// =============================================================================

// Enums (const values + types)
export * from "./enums/auth.enums.js";

// Constants
export {
  API_PREFIX,
  AUTH_API_PREFIX,
  CLIENTS_API_PREFIX,
  PROJECTS_API_PREFIX,
  TASKS_API_PREFIX,
  INVOICES_API_PREFIX,
  AI_API_PREFIX,
  FILES_API_PREFIX,
  CALENDAR_API_PREFIX,
  TEAM_API_PREFIX,
  REPORTS_API_PREFIX,
  NOTIFICATIONS_API_PREFIX,
  COMMUNICATION_API_PREFIX,
  SECURITY_API_PREFIX,
  SETTINGS_API_PREFIX,
  INTEGRATIONS_API_PREFIX,
  AUTH_COOKIES,
  AUTH_ERROR_CODES,
  AUTH_HEADERS,
  OTP_RULES,
  PASSWORD_RULES,
  RATE_LIMIT,
  RECAPTCHA,
  ROLE_DASHBOARD_ROUTES,
  TOKEN_EXPIRATION,
} from "./constants/auth.constants.js";

export type { AuthErrorCode } from "./constants/auth.constants.js";

export {
  ALL_PERMISSION_KEYS,
  MODULE_PERMISSIONS,
  PERMISSIONS,
  ROUTE_PERMISSIONS,
} from "./constants/permissions.js";

export type { ModuleKey, PermissionKey } from "./constants/permissions.js";

export {
  ADMIN_ROLES,
  DASHBOARD_ROLES,
  PORTAL_ROLES,
  ROLE_HIERARCHY,
  ROLE_LABELS,
} from "./constants/roles.js";

export {
  canAccessModule,
  canAccessRoute,
  hasAllPermissions,
  hasAnyPermission,
  hasAnyRole,
  hasMinimumRole,
  hasPermission,
  hasRole,
  permissionEngine,
  resolveRoutePermission,
} from "./utils/permission-engine.js";

export type { PermissionSubject } from "./utils/permission-engine.js";

// Types — API
export type {
  ApiErrorResponse,
  ApiResponse,
  ApiResponseMeta,
  ApiSuccessResponse,
  PaginatedResponse,
  PaginationMeta,
  ValidationError,
} from "./types/api.types.js";

export { isApiErrorResponse, isApiSuccessResponse } from "./types/api.types.js";

// Types — Auth
export type {
  AccessTokenPayload,
  AuthenticatedContext,
  AuthTokens,
  ForgotPasswordRequest,
  LoginRequest,
  LoginResponse,
  OAuthCallbackRequest,
  Permission,
  RefreshTokenRequest,
  RefreshTokenResponse,
  ResendOtpRequest,
  ResendVerificationRequest,
  ResetPasswordRequest,
  Role,
  SafeUser,
  Session,
  SessionListResponse,
  SignupRequest,
  SignupResponse,
  User,
  VerifyEmailRequest,
  VerifyOtpRequest,
  VerifyOtpResponse,
} from "./types/auth.types.js";

// Types — User
export type {
  ChangePasswordRequest,
  ChangePasswordResponse,
  UpdateProfileRequest,
  UpdateProfileResponse,
  UserProfile,
} from "./types/user.types.js";

// Types — Clients
export type {
  Client,
  ClientDeleteResponse,
  ClientListResponse,
  ClientMutationResponse,
} from "./types/clients.types.js";

// Types — Projects
export type {
  Project,
  ProjectListResponse,
  ProjectStats,
} from "./types/projects.types.js";

// Types — Tasks
export type {
  Task,
  TaskListResponse,
  TaskStats,
} from "./types/tasks.types.js";

// Types — Invoices
export type {
  Invoice,
  InvoiceListResponse,
  InvoiceStats,
} from "./types/invoices.types.js";

// Types — AI
export type {
  AiConversation,
  AiConversationListResponse,
  AiDocument,
  AiDocumentListResponse,
  AiMessage,
} from "./types/ai.types.js";

// Types — Files
export type {
  Folder,
  FolderListResponse,
  ManagedFile,
  ManagedFileListResponse,
} from "./types/files.types.js";

export type {
  CalendarEvent,
  CalendarEventListResponse,
  Holiday,
  HolidayListResponse,
  UpcomingEventsResponse,
} from "./types/calendar.types.js";

export type {
  Attendance,
  AttendanceListResponse,
  Department,
  DepartmentListResponse,
  EmployeeGoal,
  EmployeeListResponse,
  EmployeeProfile,
  GoalListResponse,
  LeaveListResponse,
  LeaveRequest,
  PerformanceListResponse,
  PerformanceReview,
  Team,
  TeamListResponse,
  TeamStatistics,
} from "./types/team.types.js";

export type {
  AiInsight,
  AnalyticsDashboard,
  ReportTemplate,
  ReportTemplateListResponse,
  SavedReport,
  SavedReportListResponse,
} from "./types/reports.types.js";

export type {
  Notification,
  NotificationAudit,
  NotificationHistoryResponse,
  NotificationListResponse,
  NotificationPreference,
  NotificationPreferenceListResponse,
  NotificationQueueItem,
  NotificationQueueListResponse,
  NotificationReply,
  NotificationTemplate,
  NotificationTemplateListResponse,
  UnreadCount,
} from "./types/notifications.types.js";

// Schemas — Common primitives
export {
  avatarUrlSchema,
  emailSchema,
  firstNameSchema,
  lastNameSchema,
  otpCodeSchema,
  passwordSchema,
  tokenSchema,
  uuidSchema,
  withPasswordConfirmation,
} from "./schemas/common.schema.js";

// Schemas — Auth
export {
  authTokensSchema,
  forgotPasswordSchema,
  loginResponseSchema,
  loginSchema,
  oauthCallbackSchema,
  oauthLinkSchema,
  oauthUnlinkSchema,
  refreshTokenSchema,
  resendOtpSchema,
  resendVerificationSchema,
  resetPasswordApiSchema,
  resetPasswordSchema,
  revokeSessionParamsSchema,
  renameSessionSchema,
  renameSessionParamsSchema,
  safeUserSchema,
  signupSchema,
  verifyEmailQuerySchema,
  verifyEmailSchema,
  verifyOtpSchema,
} from "./schemas/auth.schema.js";

export type {
  ForgotPasswordInput,
  LoginInput,
  LoginResponseOutput,
  OAuthCallbackInput,
  OAuthLinkInput,
  OAuthUnlinkInput,
  RefreshTokenInput,
  ResendOtpInput,
  ResendVerificationInput,
  ResetPasswordApiInput,
  ResetPasswordInput,
  RevokeSessionParamsInput,
  RenameSessionInput,
  RenameSessionParamsInput,
  SignupInput,
  VerifyEmailInput,
  VerifyEmailQueryInput,
  VerifyOtpInput,
} from "./schemas/auth.schema.js";

// Schemas — User
export {
  changePasswordSchema,
  updateProfileSchema,
  userProfileSchema,
} from "./schemas/user.schema.js";

export type {
  ChangePasswordInput,
  UpdateProfileInput,
  UserProfileOutput,
} from "./schemas/user.schema.js";

// Schemas — Clients
export {
  CLIENT_SORT_FIELDS,
  CLIENT_STATUSES,
  clientFieldsSchema,
  clientIdParamsSchema,
  clientSchema,
  clientStatusSchema,
  createClientSchema,
  listClientsQuerySchema,
  updateClientSchema,
} from "./schemas/clients.schema.js";

export type {
  ClientDto,
  ClientIdParamsInput,
  ClientStatusValue,
  CreateClientInput,
  ListClientsQueryInput,
  UpdateClientInput,
} from "./schemas/clients.schema.js";

// Schemas — Projects
export {
  MILESTONE_STATUSES,
  PROJECT_PRIORITIES,
  PROJECT_SORT_FIELDS,
  PROJECT_STATUSES,
  createProjectSchema,
  listProjectsQuerySchema,
  milestoneStatusSchema,
  projectAttachmentSchema,
  projectFieldsSchema,
  projectIdParamsSchema,
  projectMemberSchema,
  projectMilestoneSchema,
  projectPrioritySchema,
  projectSchema,
  projectStatusSchema,
  updateProjectSchema,
} from "./schemas/projects.schema.js";

export type {
  CreateProjectInput,
  ListProjectsQueryInput,
  MilestoneStatusValue,
  ProjectAttachmentDto,
  ProjectDto,
  ProjectIdParamsInput,
  ProjectMemberDto,
  ProjectMilestoneDto,
  ProjectPriorityValue,
  ProjectStatusValue,
  UpdateProjectInput,
} from "./schemas/projects.schema.js";

// Schemas — Tasks
export {
  TASK_PRIORITIES,
  TASK_SORT_FIELDS,
  TASK_STATUSES,
  createTaskCommentSchema,
  createTaskSchema,
  employeeUpdateTaskSchema,
  listTasksQuerySchema,
  taskActivitySchema,
  taskAttachmentSchema,
  taskCommentSchema,
  taskFieldsSchema,
  taskIdParamsSchema,
  taskPrioritySchema,
  taskSchema,
  taskStatusSchema,
  updateTaskSchema,
} from "./schemas/tasks.schema.js";

export type {
  CreateTaskCommentInput,
  CreateTaskInput,
  EmployeeUpdateTaskInput,
  ListTasksQueryInput,
  TaskActivityDto,
  TaskAttachmentDto,
  TaskCommentDto,
  TaskDto,
  TaskIdParamsInput,
  TaskPriorityValue,
  TaskStatusValue,
  UpdateTaskInput,
} from "./schemas/tasks.schema.js";

// Schemas — Invoices
export {
  INVOICE_SORT_FIELDS,
  INVOICE_STATUSES,
  calculateInvoiceTotals,
  createInvoiceSchema,
  invoiceFieldsSchema,
  invoiceIdParamsSchema,
  invoiceItemSchema,
  invoicePaymentHistorySchema,
  invoiceSchema,
  invoiceStatusSchema,
  listInvoicesQuerySchema,
  updateInvoiceSchema,
} from "./schemas/invoices.schema.js";

export type {
  CreateInvoiceInput,
  InvoiceDto,
  InvoiceIdParamsInput,
  InvoiceItemDto,
  InvoicePaymentHistoryDto,
  InvoiceStatusValue,
  InvoiceTotals,
  ListInvoicesQueryInput,
  UpdateInvoiceInput,
} from "./schemas/invoices.schema.js";

// Schemas — AI
export {
  AI_ASSIST_MODES,
  AI_DOCUMENT_TYPES,
  AI_MESSAGE_ROLES,
  aiAssistModeSchema,
  aiChatRequestSchema,
  aiChatResponseSchema,
  aiConversationIdParamsSchema,
  aiConversationSchema,
  aiDocumentIdParamsSchema,
  aiDocumentSchema,
  aiDocumentTypeSchema,
  aiMessageRoleSchema,
  aiMessageSchema,
  createAiDocumentSchema,
  listAiConversationsQuerySchema,
  listAiDocumentsQuerySchema,
  updateAiDocumentSchema,
} from "./schemas/ai.schema.js";

export type {
  AiAssistModeValue,
  AiChatRequestInput,
  AiChatResponseDto,
  AiConversationDto,
  AiConversationIdParamsInput,
  AiDocumentDto,
  AiDocumentIdParamsInput,
  AiDocumentTypeValue,
  AiMessageDto,
  AiMessageRoleValue,
  CreateAiDocumentInput,
  ListAiConversationsQueryInput,
  ListAiDocumentsQueryInput,
  UpdateAiDocumentInput,
} from "./schemas/ai.schema.js";

// Schemas — Files
export {
  FILE_CATEGORIES,
  FILE_SHARE_ACCESS,
  FILE_SORT_FIELDS,
  createFolderSchema,
  fileActivityDtoSchema,
  fileCategorySchema,
  fileIdParamsSchema,
  fileShareAccessSchema,
  fileShareDtoSchema,
  fileVersionDtoSchema,
  folderDtoSchema,
  folderIdParamsSchema,
  listFilesQuerySchema,
  listFoldersQuerySchema,
  managedFileDtoSchema,
  moveFileSchema,
  shareFileSchema,
  shareIdParamsSchema,
  updateFileSchema,
  updateFolderSchema,
} from "./schemas/files.schema.js";

export type {
  CreateFolderInput,
  FileActivityDto,
  FileCategoryValue,
  FileIdParamsInput,
  FileShareAccessValue,
  FileShareDto,
  FileVersionDto,
  FolderDto,
  FolderIdParamsInput,
  ListFilesQueryInput,
  ListFoldersQueryInput,
  ManagedFileDto,
  MoveFileInput,
  ShareFileInput,
  ShareIdParamsInput,
  UpdateFileInput,
  UpdateFolderInput,
} from "./schemas/files.schema.js";

// Schemas — Calendar
export {
  CALENDAR_EVENT_CATEGORIES,
  CALENDAR_EVENT_STATUSES,
  CALENDAR_EVENT_TYPES,
  CALENDAR_VIEWS,
  EVENT_ATTENDEE_STATUSES,
  RECURRENCE_FREQUENCIES,
  REMINDER_CHANNELS,
  calendarEventCategorySchema,
  calendarEventDtoSchema,
  calendarEventIdParamsSchema,
  calendarEventStatusSchema,
  calendarEventTypeSchema,
  calendarViewSchema,
  createCalendarEventSchema,
  createHolidaySchema,
  eventAttendeeDtoSchema,
  eventAttendeeStatusSchema,
  eventReminderDtoSchema,
  holidayDtoSchema,
  holidayIdParamsSchema,
  listCalendarEventsQuerySchema,
  listHolidaysQuerySchema,
  moveCalendarEventSchema,
  recurrenceFrequencySchema,
  reminderChannelSchema,
  resizeCalendarEventSchema,
  respondInvitationSchema,
  updateCalendarEventSchema,
} from "./schemas/calendar.schema.js";

export type {
  CalendarEventCategoryValue,
  CalendarEventDto,
  CalendarEventIdParamsInput,
  CalendarEventStatusValue,
  CalendarEventTypeValue,
  CalendarViewValue,
  CreateCalendarEventInput,
  CreateHolidayInput,
  EventAttendeeDto,
  EventAttendeeStatusValue,
  EventReminderDto,
  HolidayDto,
  HolidayIdParamsInput,
  ListCalendarEventsQueryInput,
  ListHolidaysQueryInput,
  MoveCalendarEventInput,
  RecurrenceFrequencyValue,
  ReminderChannelValue,
  ResizeCalendarEventInput,
  RespondInvitationInput,
  UpdateCalendarEventInput,
} from "./schemas/calendar.schema.js";

// Schemas — Team
export {
  ATTENDANCE_STATUSES,
  EMPLOYEE_STATUSES,
  GOAL_STATUSES,
  LEAVE_REQUEST_STATUSES,
  LEAVE_TYPES,
  PERFORMANCE_RATINGS,
  attendanceDtoSchema,
  attendanceStatusSchema,
  checkInSchema,
  checkOutSchema,
  createDepartmentSchema,
  createEmployeeGoalSchema,
  createEmployeeProfileSchema,
  createLeaveRequestSchema,
  createPerformanceReviewSchema,
  createTeamSchema,
  departmentDtoSchema,
  departmentIdParamsSchema,
  employeeGoalDtoSchema,
  employeeIdParamsSchema,
  employeeProfileDtoSchema,
  employeeStatusSchema,
  goalIdParamsSchema,
  goalStatusSchema,
  leaveIdParamsSchema,
  leaveRequestDtoSchema,
  leaveRequestStatusSchema,
  leaveTypeSchema,
  listAttendanceQuerySchema,
  listEmployeesQuerySchema,
  listLeavesQuerySchema,
  performanceIdParamsSchema,
  performanceRatingSchema,
  performanceReviewDtoSchema,
  reviewLeaveSchema,
  teamDtoSchema,
  teamIdParamsSchema,
  teamMemberDtoSchema,
  teamMembersSchema,
  teamStatisticsDtoSchema,
  updateDepartmentSchema,
  updateEmployeeGoalSchema,
  updateEmployeeProfileSchema,
  updatePerformanceReviewSchema,
  updateTeamSchema,
} from "./schemas/team.schema.js";

export type {
  AttendanceDto,
  AttendanceStatusValue,
  CheckInInput,
  CheckOutInput,
  CreateDepartmentInput,
  CreateEmployeeGoalInput,
  CreateEmployeeProfileInput,
  CreateLeaveRequestInput,
  CreatePerformanceReviewInput,
  CreateTeamInput,
  DepartmentDto,
  DepartmentIdParamsInput,
  EmployeeGoalDto,
  EmployeeIdParamsInput,
  EmployeeProfileDto,
  EmployeeStatusValue,
  GoalIdParamsInput,
  GoalStatusValue,
  LeaveIdParamsInput,
  LeaveRequestDto,
  LeaveRequestStatusValue,
  LeaveTypeValue,
  ListAttendanceQueryInput,
  ListEmployeesQueryInput,
  ListLeavesQueryInput,
  PerformanceIdParamsInput,
  PerformanceRatingValue,
  PerformanceReviewDto,
  ReviewLeaveInput,
  TeamDto,
  TeamIdParamsInput,
  TeamMemberDto,
  TeamMembersInput,
  TeamStatisticsDto,
  UpdateDepartmentInput,
  UpdateEmployeeGoalInput,
  UpdateEmployeeProfileInput,
  UpdatePerformanceReviewInput,
  UpdateTeamInput,
} from "./schemas/team.schema.js";

// Schemas — Reports
export {
  REPORT_CATEGORIES,
  REPORT_DATE_RANGES,
  REPORT_EXPORT_FORMATS,
  REPORT_VISIBILITIES,
  analyticsDashboardDtoSchema,
  analyticsQuerySchema,
  aiInsightDtoSchema,
  chartPointSchema,
  createSavedReportSchema,
  exportReportSchema,
  kpiCardSchema,
  reportCategorySchema,
  reportDateRangeSchema,
  reportExportFormatSchema,
  reportFiltersSchema,
  reportTemplateDtoSchema,
  reportVisibilitySchema,
  savedReportDtoSchema,
  savedReportIdParamsSchema,
  updateSavedReportSchema,
} from "./schemas/reports.schema.js";

export type {
  AiInsightDto,
  AnalyticsDashboardDto,
  AnalyticsQueryInput,
  ChartPoint,
  CreateSavedReportInput,
  ExportReportInput,
  KpiCard,
  ReportCategoryValue,
  ReportDateRangeValue,
  ReportExportFormatValue,
  ReportFiltersInput,
  ReportTemplateDto,
  ReportVisibilityValue,
  SavedReportDto,
  SavedReportIdParamsInput,
  UpdateSavedReportInput,
} from "./schemas/reports.schema.js";

// Schemas — Notifications
export {
  NOTIFICATION_AUDIENCE_TYPES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_QUEUE_STATUSES,
  bulkNotificationIdsSchema,
  createNotificationSchema,
  listHistoryQuerySchema,
  listNotificationsQuerySchema,
  listQueueQuerySchema,
  notificationAudienceTypeSchema,
  notificationAuditDtoSchema,
  notificationCategorySchema,
  notificationChannelSchema,
  notificationDtoSchema,
  notificationIdParamsSchema,
  notificationPreferenceDtoSchema,
  notificationPrioritySchema,
  notificationQueueDtoSchema,
  notificationQueueStatusSchema,
  notificationTemplateDtoSchema,
  unreadCountDtoSchema,
  updatePreferenceSchema,
  updatePreferencesBatchSchema,
  notificationReplyDtoSchema,
  notificationReplyListResponseSchema,
  createNotificationReplySchema,
  notificationReplyIdParamsSchema,
} from "./schemas/notifications.schema.js";

export type {
  BulkNotificationIdsInput,
  CreateNotificationInput,
  ListHistoryQueryInput,
  ListNotificationsQueryInput,
  ListQueueQueryInput,
  NotificationAudienceTypeValue,
  NotificationAuditDto,
  NotificationCategoryValue,
  NotificationChannelValue,
  NotificationDto,
  NotificationIdParamsInput,
  NotificationPreferenceDto,
  NotificationPriorityValue,
  NotificationQueueDto,
  NotificationQueueStatusValue,
  NotificationTemplateDto,
  UnreadCountDto,
  UpdatePreferenceInput,
  UpdatePreferencesBatchInput,
  NotificationReplyDto,
  NotificationReplyListResponse,
  CreateNotificationReplyInput,
  NotificationReplyIdParamsInput,
} from "./schemas/notifications.schema.js";

// Types — Communication
export type {
  Activity,
  ActivityListResponse,
  Announcement,
  AnnouncementListResponse,
  Comment,
  CommentListResponse,
  CommunicationAiResponse,
  CommunicationPagination,
  CommunicationSearchResponse,
  Conversation,
  ConversationListResponse,
  DiscussionReply,
  DiscussionThread,
  DiscussionThreadListResponse,
  MeetingRoom,
  MeetingRoomListResponse,
  Message,
  MessageListResponse,
  UserPresence,
} from "./types/communication.types.js";

// Schemas — Communication
export {
  ACTIVITY_ENTITY_TYPES,
  COMMENT_ENTITY_TYPES,
  CONVERSATION_MEMBER_ROLES,
  CONVERSATION_TYPES,
  MESSAGE_KINDS,
  MESSAGE_READ_STATUSES,
  activityAttachmentDtoSchema,
  activityDtoSchema,
  activityEntityTypeSchema,
  addConversationMembersSchema,
  commentAttachmentDtoSchema,
  commentDtoSchema,
  commentEntityTypeSchema,
  commentIdParamsSchema,
  communicationSearchQuerySchema,
  communicationUserSummarySchema,
  conversationDtoSchema,
  conversationIdParamsSchema,
  conversationMemberDtoSchema,
  conversationMemberParamsSchema,
  conversationMemberRoleSchema,
  conversationTypeSchema,
  createCommentSchema,
  createConversationSchema,
  createMessageSchema,
  forwardMessageSchema,
  listActivitiesQuerySchema,
  listCommentsQuerySchema,
  listConversationsQuerySchema,
  listMessagesQuerySchema,
  markMessagesReadSchema,
  messageAttachmentDtoSchema,
  messageDtoSchema,
  messageIdParamsSchema,
  messageKindSchema,
  messageReactionDtoSchema,
  messageReadDtoSchema,
  messageReadStatusSchema,
  reactToMessageSchema,
  typingSchema,
  updateCommentSchema,
  updateConversationMemberSchema,
  updateConversationSchema,
  updateMessageSchema,
  userPresenceDtoSchema,
} from "./schemas/communication.schema.js";

export type {
  ActivityAttachmentDto,
  ActivityDto,
  ActivityEntityTypeValue,
  AddConversationMembersInput,
  AttachmentInput,
  CommentAttachmentDto,
  CommentDto,
  CommentEntityTypeValue,
  CommentIdParamsInput,
  CommunicationSearchQueryInput,
  ConversationDto,
  ConversationIdParamsInput,
  ConversationMemberDto,
  ConversationMemberParamsInput,
  ConversationMemberRoleValue,
  ConversationTypeValue,
  CreateCommentInput,
  CreateConversationInput,
  CreateMessageInput,
  ForwardMessageInput,
  ListActivitiesQueryInput,
  ListCommentsQueryInput,
  ListConversationsQueryInput,
  ListMessagesQueryInput,
  MarkMessagesReadInput,
  MessageAttachmentDto,
  MessageDto,
  MessageIdParamsInput,
  MessageKindValue,
  MessageReactionDto,
  MessageReadDto,
  MessageReadStatusValue,
  ReactToMessageInput,
  TypingInput,
  UpdateCommentInput,
  UpdateConversationInput,
  UpdateConversationMemberInput,
  UpdateMessageInput,
  UserPresenceDto,
} from "./schemas/communication.schema.js";

// Schemas — Communication Hub (Phase 20)
export {
  ANNOUNCEMENT_PRIORITIES,
  COMMUNICATION_AI_ACTIONS,
  DISCUSSION_THREAD_STATUSES,
  MEETING_PARTICIPANT_STATUSES,
  MEETING_STATUSES,
  announcementAttachmentDtoSchema,
  announcementDtoSchema,
  announcementIdParamsSchema,
  announcementPrioritySchema,
  communicationAiActionSchema,
  communicationAiRequestSchema,
  communicationAiResponseSchema,
  createAnnouncementSchema,
  createDiscussionReplySchema,
  createDiscussionThreadSchema,
  createMeetingRecordingSchema,
  createMeetingRoomSchema,
  createMeetingScreenShareSchema,
  discussionReplyDtoSchema,
  discussionThreadDtoSchema,
  discussionThreadStatusSchema,
  listAnnouncementsQuerySchema,
  listDiscussionThreadsQuerySchema,
  listMeetingsQuerySchema,
  meetingIdParamsSchema,
  meetingParticipantDtoSchema,
  meetingParticipantStatusSchema,
  meetingRecordingDtoSchema,
  meetingRoomDtoSchema,
  meetingScreenShareDtoSchema,
  meetingStatusSchema,
  replyIdParamsSchema,
  threadIdParamsSchema,
  updateAnnouncementSchema,
  updateDiscussionThreadSchema,
  updateMeetingParticipantSchema,
  updateMeetingRoomSchema,
} from "./schemas/communication-hub.schema.js";

export type {
  AnnouncementAttachmentDto,
  AnnouncementDto,
  AnnouncementIdParamsInput,
  AnnouncementPriorityValue,
  CommunicationAiActionValue,
  CommunicationAiRequestInput,
  CommunicationAiResponseDto,
  CreateAnnouncementInput,
  CreateDiscussionReplyInput,
  CreateDiscussionThreadInput,
  CreateMeetingRecordingInput,
  CreateMeetingRoomInput,
  CreateMeetingScreenShareInput,
  DiscussionReplyDto,
  DiscussionThreadDto,
  DiscussionThreadStatusValue,
  ListAnnouncementsQueryInput,
  ListDiscussionThreadsQueryInput,
  ListMeetingsQueryInput,
  MeetingIdParamsInput,
  MeetingParticipantDto,
  MeetingParticipantStatusValue,
  MeetingRecordingDto,
  MeetingRoomDto,
  MeetingScreenShareDto,
  MeetingStatusValue,
  ReplyIdParamsInput,
  ThreadIdParamsInput,
  UpdateAnnouncementInput,
  UpdateDiscussionThreadInput,
  UpdateMeetingParticipantInput,
  UpdateMeetingRoomInput,
} from "./schemas/communication-hub.schema.js";

// Types — Security
export type {
  ActiveDeviceDto,
  ActiveDeviceListResponse,
  ChangePasswordSecurityResponse,
  ContactFormResponse,
  CsrfTokenResponse,
  LoginHistoryDto,
  LoginHistoryListResponse,
  PasswordHistoryItemDto,
  PasswordHistoryListResponse,
  PasswordStatusDto,
  SecurityAuditLogDto,
  SecurityAuditLogListResponse,
  SecurityDashboardDto,
  SecurityEventDto,
  SecurityEventListResponse,
  SecurityPagination,
  SecurityScoreDto,
  UnlockAccountResponse,
} from "./types/security.types.js";

// Schemas — Security
export {
  SECURITY_EVENT_CATEGORIES,
  SECURITY_SEVERITIES,
  activeDeviceDtoSchema,
  captchaTokenSchema,
  contactFormSchema,
  listActiveSessionsQuerySchema,
  listLoginHistoryQuerySchema,
  listSecurityEventsQuerySchema,
  listSecurityLogsQuerySchema,
  loginHistoryDtoSchema,
  passwordHistoryItemDtoSchema,
  passwordStatusDtoSchema,
  resolveSecurityEventParamsSchema,
  securityAuditLogDtoSchema,
  securityDashboardDtoSchema,
  securityEventCategorySchema,
  securityEventDtoSchema,
  securityScoreDtoSchema,
  securitySeveritySchema,
  terminateSessionParamsSchema,
  unlockAccountSchema,
} from "./schemas/security.schema.js";

export type {
  ContactFormInput,
  ListActiveSessionsQueryInput,
  ListLoginHistoryQueryInput,
  ListSecurityEventsQueryInput,
  ListSecurityLogsQueryInput,
  ResolveSecurityEventParamsInput,
  TerminateSessionParamsInput,
  UnlockAccountInput,
} from "./schemas/security.schema.js";

// Types — Settings
export type {
  AiSettingsDto,
  AppearanceSettingsDto,
  AppLanguageCode,
  BackupRecordDto,
  BillingSettingsDto,
  CompanySettingsDto,
  IntegrationCredentialDto,
  LocaleSettingsDto,
  NotificationSettingsDto,
  SecurityPreferencesDto,
  SettingsOverviewDto,
  SettingsProfileDto,
  StorageSettingsDto,
  UpdateAiSettingsInput,
  UpdateAppearanceSettingsInput,
  UpdateCompanySettingsInput,
  UpdateLocaleSettingsInput,
  UpdateNotificationSettingsInput,
  UpdateSecurityPreferencesInput,
  UpdateSettingsProfileInput,
} from "./types/settings.types.js";

// Schemas — Settings
export {
  APP_LANGUAGES,
  BORDER_RADII,
  DASHBOARD_DENSITIES,
  FONT_SIZES,
  INTEGRATION_PROVIDERS,
  SIDEBAR_STYLES,
  THEME_MODES,
  appLanguageSchema,
  backupIdParamsSchema,
  borderRadiusSchema,
  createBackupSchema,
  createIntegrationCredentialSchema,
  dashboardDensitySchema,
  fontSizeSchema,
  integrationCredentialIdParamsSchema,
  integrationProviderSchema,
  requestAccountDeletionSchema,
  settingsProfileDtoSchema,
  sidebarStyleSchema,
  themeModeSchema,
  updateAiSettingsSchema,
  updateAppearanceSettingsSchema,
  updateBillingSettingsSchema,
  updateCompanySettingsSchema,
  updateIntegrationCredentialSchema,
  updateLocaleSettingsSchema,
  updateNotificationSettingsSchema,
  updateSecurityPreferencesSchema,
  updateSettingsProfileSchema,
} from "./schemas/settings.schema.js";

export type {
  BackupIdParamsInput,
  CreateBackupInput,
  CreateIntegrationCredentialInput,
  IntegrationCredentialIdParamsInput,
  RequestAccountDeletionInput,
  UpdateBillingSettingsInput,
  UpdateIntegrationCredentialInput,
} from "./schemas/settings.schema.js";

// Types — Integrations (Phase 19.1)
export type {
  IntegrationConnectResponse,
  IntegrationDetailDto,
  IntegrationDisconnectResponse,
  IntegrationDto,
  IntegrationLogDto,
  IntegrationLogListResponse,
  IntegrationLogLevelValue,
  IntegrationOverviewDto,
  IntegrationConnectionStatusValue,
  IntegrationHealthStatusValue,
  IntegrationSyncStatusValue,
  IntegrationTestResponse,
  IntegrationApiUsageDto,
  IntegrationHealthTimelinePoint,
  SyncHistoryDto,
  SyncHistoryListResponse,
  WebhookEndpointDto,
} from "./types/integrations.types.js";

export type {
  IntegrationOAuthConnectResponse,
  IntegrationOverviewKpis,
  IntegrationProviderStatusDto,
  OAuthIntegrationProvider,
  ApiKeyIntegrationProvider,
  IntegrationProviderRoute,
} from "./types/integrations-oauth.types.js";

export type {
  IntegrationLiveMonitoringDto,
  IntegrationMonitoringOverviewDto,
  SyncQueueJobDto,
  SyncQueueOverviewDto,
  SyncSchedulerConfigDto,
  SyncSchedulerPresetValue,
  WebhookMonitorOverviewDto,
  IntegrationUsageAnalyticsDto,
  IntegrationAlertDto,
  IntegrationAlertListResponse,
  IntegrationAlertTypeValue,
  IntegrationAlertSeverityValue,
  IntegrationPlatformDetailDto,
} from "./types/integrations-monitoring.types.js";

// Schemas — Integrations (Phase 19.1 / 19.2)
export {
  INTEGRATION_CONNECTION_STATUSES,
  INTEGRATION_HEALTH_STATUSES,
  INTEGRATION_LOG_LEVELS,
  INTEGRATION_SLUGS,
  INTEGRATION_SYNC_STATUSES,
  OAUTH_INTEGRATION_PROVIDERS,
  API_KEY_INTEGRATION_PROVIDERS,
  AI_PROVIDER_IDS,
  SYNC_SCHEDULER_PRESETS,
  INTEGRATION_ALERT_TYPES,
  INTEGRATION_ALERT_SEVERITIES,
  connectIntegrationSchema,
  connectApiKeyIntegrationSchema,
  disconnectIntegrationSchema,
  integrationConnectionStatusSchema,
  integrationHealthStatusSchema,
  integrationIdParamsSchema,
  integrationSlugParamsSchema,
  integrationLogLevelSchema,
  integrationSlugSchema,
  integrationSyncStatusSchema,
  listIntegrationLogsQuerySchema,
  listIntegrationsQuerySchema,
  listSyncHistoryQuerySchema,
  listIntegrationAlertsQuerySchema,
  oauthCallbackQuerySchema,
  oauthIntegrationProviderSchema,
  oauthProviderParamsSchema,
  apiKeyIntegrationProviderSchema,
  apiKeyProviderParamsSchema,
  aiProviderIdSchema,
  syncSchedulerPresetSchema,
  integrationAlertTypeSchema,
  integrationAlertSeveritySchema,
  updateSchedulerConfigSchema,
  syncJobIdParamsSchema,
  acknowledgeAlertSchema,
  manualSyncSchema,
  testIntegrationSchema,
} from "./schemas/integrations.schema.js";

export type {
  ConnectIntegrationInput,
  ConnectApiKeyIntegrationInput,
  DisconnectIntegrationInput,
  IntegrationIdParamsInput,
  IntegrationSlugParamsInput,
  ListIntegrationLogsQueryInput,
  ListIntegrationsQueryInput,
  ListSyncHistoryQueryInput,
  ListIntegrationAlertsQueryInput,
  OAuthCallbackQueryInput,
  OAuthIntegrationProviderValue,
  OAuthProviderParamsInput,
  ApiKeyIntegrationProviderValue,
  ApiKeyProviderParamsInput,
  AiProviderIdValue,
  UpdateSchedulerConfigInput,
  SyncJobIdParamsInput,
  AcknowledgeAlertInput,
  ManualSyncInput,
  TestIntegrationInput,
} from "./schemas/integrations.schema.js";
