// =============================================================================
// @enterprise/shared — Barrel Exports
// =============================================================================
// Import from '@enterprise/shared' only. No deep imports.
// =============================================================================

// Enums (const values + types)
export * from "./enums/auth.enums.js";

// Constants
export {
  API_PREFIX,
  AUTH_API_PREFIX,
  CLIENTS_API_PREFIX,
  PROJECTS_API_PREFIX,
  TASKS_API_PREFIX,
  INVOICES_API_PREFIX,
  BILLING_API_PREFIX,
  AI_API_PREFIX,
  FILES_API_PREFIX,
  CALENDAR_API_PREFIX,
  TEAM_API_PREFIX,
  REPORTS_API_PREFIX,
  NOTIFICATIONS_API_PREFIX,
  COMMUNICATION_API_PREFIX,
  SECURITY_API_PREFIX,
  SETTINGS_API_PREFIX,
  SEARCH_API_PREFIX,
  INTEGRATIONS_API_PREFIX,
  WHITEBOARDS_API_PREFIX,
  CUSTOMER_REQUESTS_API_PREFIX,
  QUOTES_API_PREFIX,
  AUTH_COOKIES,
  AUTH_ERROR_CODES,
  AUTH_HEADERS,
  OTP_RULES,
  PASSWORD_RULES,
  RATE_LIMIT,
  RECAPTCHA,
  ROLE_DASHBOARD_ROUTES,
  TOKEN_EXPIRATION,
} from "./constants/auth.constants.js";

export type { AuthErrorCode } from "./constants/auth.constants.js";

export {
  ALL_PERMISSION_KEYS,
  MODULE_PERMISSIONS,
  PERMISSIONS,
  ROUTE_PERMISSIONS,
} from "./constants/permissions.js";

export type { ModuleKey, PermissionKey } from "./constants/permissions.js";

export {
  ADMIN_ROLES,
  DASHBOARD_ROLES,
  PORTAL_ROLES,
  ROLE_HIERARCHY,
  ROLE_LABELS,
} from "./constants/roles.js";

export {
  canAccessModule,
  canAccessRoute,
  hasAllPermissions,
  hasAnyPermission,
  hasAnyRole,
  hasMinimumRole,
  hasPermission,
  hasRole,
  permissionEngine,
  resolveRoutePermission,
} from "./utils/permission-engine.js";

export type { PermissionSubject } from "./utils/permission-engine.js";

export {
  DIRECTORY_OMIT_FIELDS,
  NEVER_EXPOSE_FIELDS,
  RESTRICTED_EMPLOYEE_FIELDS,
  RESTRICTED_PROMOTION_FIELDS,
  applyCredentialRevealPolicy,
  applyEmployeeDtoFieldPolicy,
  applyPromotionDtoFieldPolicy,
  canReadEmployeeField,
  canReadRestrictedEmployeeFields,
  canReadRestrictedPromotionFields,
  canRevealTemporaryPassword,
  canRevealPasswordSetup,
  resolveEmployeeDtoView,
} from "./security/field-authorization.js";

export type {
  EmployeeDtoView,
  FieldAccessActor,
  FieldAccessSubject,
  RestrictedEmployeeField,
  RestrictedPromotionField,
} from "./security/field-authorization.js";

export {
  CLASSIFICATION_TRUST_REQUIREMENTS,
  DATA_CLASSIFICATIONS,
} from "./security/data-classification.js";

export type { DataClassification } from "./security/data-classification.js";

export {
  CONFIDENTIAL_FIELD_KEY_RE,
  FIELD_UPDATED,
  MASKED_SALARY,
  REDACTED,
  RESTRICTED_FIELD_KEY_RE,
  SECRET_FIELD_KEY_RE,
  applyResponseMasking,
  formatLogArgs,
  maskAddress,
  maskDateOfBirth,
  maskEmail,
  maskNationalId,
  maskPhone,
  maskSalary,
  redactSecret,
  sanitizeAuditMetadata,
  sanitizeForLogging,
  sanitizeSensitiveData,
  scrubSensitiveString,
} from "./security/data-redaction.js";

export type { RedactionMode } from "./security/data-redaction.js";

export {
  FORBIDDEN_ATTACHMENT_URL_SCHEMES,
  buildInternalManagedFileDownloadPath,
  hasForbiddenAttachmentUrlScheme,
  isAttachmentUrlSchemeAllowed,
  parseInternalManagedFileId,
} from "./utils/attachment-url.js";

// Types — API
export type {
  ApiErrorResponse,
  ApiResponse,
  ApiResponseMeta,
  ApiSuccessResponse,
  PaginatedResponse,
  PaginationMeta,
  ValidationError,
} from "./types/api.types.js";

export { isApiErrorResponse, isApiSuccessResponse } from "./types/api.types.js";

// Types — Auth
export type {
  AccessTokenPayload,
  AuthenticatedContext,
  AuthTokens,
  ForgotPasswordRequest,
  LoginRequest,
  LoginResponse,
  OAuthCallbackRequest,
  Permission,
  RefreshTokenRequest,
  RefreshTokenResponse,
  ResendOtpRequest,
  ResendVerificationRequest,
  ResetPasswordRequest,
  Role,
  SafeUser,
  Session,
  SessionListResponse,
  SignupRequest,
  SignupResponse,
  User,
  VerifyEmailRequest,
  VerifyOtpRequest,
  VerifyOtpResponse,
} from "./types/auth.types.js";

// Types — User
export type {
  ChangePasswordRequest,
  ChangePasswordResponse,
  UpdateProfileRequest,
  UpdateProfileResponse,
  UserProfile,
} from "./types/user.types.js";

// Types — Clients
export type {
  Client,
  ClientDeleteResponse,
  ClientListResponse,
  ClientMutationResponse,
} from "./types/clients.types.js";

// Types — Projects
export type {
  Project,
  ProjectListResponse,
  ProjectStats,
} from "./types/projects.types.js";

// Types — Tasks
export type {
  Task,
  TaskListResponse,
  TaskStats,
} from "./types/tasks.types.js";

// Types — Invoices
export type {
  Invoice,
  InvoiceListResponse,
  InvoiceStats,
} from "./types/invoices.types.js";

// Types — Quotes
export type {
  Quote,
  QuoteListResponse,
} from "./types/quotes.types.js";

// Types — AI
export type {
  AiConversation,
  AiConversationListResponse,
  AiDocument,
  AiDocumentListResponse,
  AiMessage,
} from "./types/ai.types.js";

// Types — Files
export type {
  Folder,
  FolderListResponse,
  ManagedFile,
  ManagedFileListResponse,
} from "./types/files.types.js";

export type {
  CalendarEvent,
  CalendarEventListResponse,
  Holiday,
  HolidayListResponse,
  UpcomingEventsResponse,
} from "./types/calendar.types.js";

export type {
  Attendance,
  AttendanceListResponse,
  Department,
  DepartmentListResponse,
  EmployeeGoal,
  EmployeeListResponse,
  EmployeeProfile,
  GoalListResponse,
  LeaveListResponse,
  LeaveRequest,
  PerformanceListResponse,
  PerformanceReview,
  Team,
  TeamListResponse,
  TeamStatistics,
} from "./types/team.types.js";

export type {
  AiInsight,
  AnalyticsDashboard,
  ReportTemplate,
  ReportTemplateListResponse,
  SavedReport,
  SavedReportListResponse,
} from "./types/reports.types.js";

export type {
  Notification,
  NotificationAudit,
  NotificationHistoryResponse,
  NotificationListResponse,
  NotificationPreference,
  NotificationPreferenceListResponse,
  NotificationQueueItem,
  NotificationQueueListResponse,
  NotificationReply,
  NotificationTemplate,
  NotificationTemplateListResponse,
  UnreadCount,
} from "./types/notifications.types.js";

// Schemas — Common primitives
export {
  avatarUrlSchema,
  emailSchema,
  firstNameSchema,
  lastNameSchema,
  otpCodeSchema,
  mfaChallengeCodeSchema,
  passwordSchema,
  tokenSchema,
  uuidSchema,
  withPasswordConfirmation,
} from "./schemas/common.schema.js";

// Schemas — Auth
export {
  authTokensSchema,
  forgotPasswordSchema,
  loginResponseSchema,
  loginSchema,
  mfaDisableSchema,
  mfaEnableSchema,
  mfaStepUpSchema,
  mfaStepUpResponseSchema,
  mfaStatusSchema,
  oauthCallbackSchema,
  oauthLinkSchema,
  oauthUnlinkSchema,
  refreshTokenSchema,
  resendOtpSchema,
  resendVerificationSchema,
  resetPasswordApiSchema,
  resetPasswordSchema,
  revokeSessionParamsSchema,
  renameSessionSchema,
  renameSessionParamsSchema,
  safeUserSchema,
  signupSchema,
  verifyEmailQuerySchema,
  verifyEmailSchema,
  verifyOtpSchema,
} from "./schemas/auth.schema.js";

export type {
  ForgotPasswordInput,
  LoginInput,
  LoginResponseOutput,
  MfaDisableInput,
  MfaEnableInput,
  MfaStepUpInput,
  MfaStepUpResponse,
  MfaStatusOutput,
  OAuthCallbackInput,
  OAuthLinkInput,
  OAuthUnlinkInput,
  RefreshTokenInput,
  ResendOtpInput,
  ResendVerificationInput,
  ResetPasswordApiInput,
  ResetPasswordInput,
  RevokeSessionParamsInput,
  RenameSessionInput,
  RenameSessionParamsInput,
  SignupInput,
  VerifyEmailInput,
  VerifyEmailQueryInput,
  VerifyOtpInput,
} from "./schemas/auth.schema.js";

// Schemas — User
export {
  changePasswordSchema,
  updateProfileSchema,
  userProfileSchema,
} from "./schemas/user.schema.js";

export type {
  ChangePasswordInput,
  UpdateProfileInput,
  UserProfileOutput,
} from "./schemas/user.schema.js";

// Schemas — Clients
export {
  CLIENT_ACTIVITY_TYPES,
  CLIENT_PIPELINE_STAGES,
  CLIENT_SORT_FIELDS,
  CLIENT_STATUSES,
  clientActivityIdParamsSchema,
  clientActivitySchema,
  clientActivityTypeSchema,
  clientFieldsSchema,
  clientIdParamsSchema,
  clientPipelineBoardSchema,
  clientPipelineStageSchema,
  clientSchema,
  clientStatusSchema,
  createClientActivitySchema,
  createClientSchema,
  linkPortalUserSchema,
  listClientActivitiesQuerySchema,
  listClientsQuerySchema,
  listUnlinkedPortalUsersQuerySchema,
  portalUserIdParamsSchema,
  portalUserSchema,
  updateClientPipelineStageSchema,
  updateClientSchema,
} from "./schemas/clients.schema.js";

export type {
  ClientActivityDto,
  ClientActivityIdParamsInput,
  ClientActivityTypeValue,
  ClientDto,
  ClientIdParamsInput,
  ClientPipelineBoardDto,
  ClientPipelineColumnDto,
  ClientPipelineStageValue,
  ClientStatusValue,
  CreateClientActivityInput,
  CreateClientInput,
  LinkPortalUserInput,
  ListClientActivitiesQueryInput,
  ListClientsQueryInput,
  ListUnlinkedPortalUsersQueryInput,
  PortalUserDto,
  PortalUserIdParamsInput,
  UpdateClientInput,
  UpdateClientPipelineStageInput,
} from "./schemas/clients.schema.js";

// Schemas — Projects
export {
  MILESTONE_STATUSES,
  PROJECT_PRIORITIES,
  PROJECT_SORT_FIELDS,
  PROJECT_STATUSES,
  createProjectSchema,
  listProjectsQuerySchema,
  milestoneStatusSchema,
  projectAttachmentSchema,
  projectFieldsSchema,
  projectIdParamsSchema,
  projectMemberSchema,
  projectMilestoneSchema,
  projectPrioritySchema,
  projectSchema,
  projectStatusSchema,
  updateProjectSchema,
} from "./schemas/projects.schema.js";

export type {
  CreateProjectInput,
  ListProjectsQueryInput,
  MilestoneStatusValue,
  ProjectAttachmentDto,
  ProjectDto,
  ProjectIdParamsInput,
  ProjectMemberDto,
  ProjectMilestoneDto,
  ProjectPriorityValue,
  ProjectStatusValue,
  UpdateProjectInput,
} from "./schemas/projects.schema.js";

// Schemas — Tasks
export {
  TASK_PRIORITIES,
  TASK_SORT_FIELDS,
  TASK_STATUSES,
  createTaskCommentSchema,
  createTaskSchema,
  employeeUpdateTaskSchema,
  listTasksQuerySchema,
  taskActivitySchema,
  taskAttachmentSchema,
  taskCommentSchema,
  taskFieldsSchema,
  taskIdParamsSchema,
  taskPrioritySchema,
  taskSchema,
  taskStatusSchema,
  updateTaskSchema,
} from "./schemas/tasks.schema.js";

export type {
  CreateTaskCommentInput,
  CreateTaskInput,
  EmployeeUpdateTaskInput,
  ListTasksQueryInput,
  TaskActivityDto,
  TaskAttachmentDto,
  TaskCommentDto,
  TaskDto,
  TaskIdParamsInput,
  TaskPriorityValue,
  TaskStatusValue,
  UpdateTaskInput,
} from "./schemas/tasks.schema.js";

// Schemas — Invoices
export {
  INVOICE_COMMERCIAL_MUTATION_STATUSES,
  INVOICE_KINDS,
  INVOICE_PAYMENT_STATUSES,
  INVOICE_SORT_FIELDS,
  INVOICE_STATUSES,
  calculateInvoiceTotals,
  createInvoiceSchema,
  invoiceCommercialMutationStatusSchema,
  invoiceFieldsSchema,
  invoiceIdParamsSchema,
  invoiceItemSchema,
  invoiceKindSchema,
  invoicePaymentHistorySchema,
  invoicePaymentNoticeSchema,
  invoicePaymentStatusSchema,
  invoiceSchema,
  invoiceStatusSchema,
  listInvoicesQuerySchema,
  updateInvoiceSchema,
} from "./schemas/invoices.schema.js";

export type {
  CreateInvoiceInput,
  InvoiceDto,
  InvoiceIdParamsInput,
  InvoiceItemDto,
  InvoiceKindValue,
  InvoicePaymentHistoryDto,
  InvoicePaymentNoticeInput,
  InvoicePaymentStatusValue,
  InvoiceStatusValue,
  InvoiceTotals,
  ListInvoicesQueryInput,
  UpdateInvoiceInput,
} from "./schemas/invoices.schema.js";

// Schemas — AI
export {
  AI_ASSIST_MODES,
  AI_DOCUMENT_TYPES,
  AI_MESSAGE_ROLES,
  aiAssistModeSchema,
  aiChatRequestSchema,
  aiChatResponseSchema,
  aiConfirmationDecisionResponseSchema,
  aiConfirmationIdParamsSchema,
  aiConfirmationRequiredSchema,
  aiConfirmationRiskLevelSchema,
  aiConversationIdParamsSchema,
  aiConversationSchema,
  aiDocumentIdParamsSchema,
  aiDocumentSchema,
  aiDocumentTypeSchema,
  aiMessageRoleSchema,
  aiMessageSchema,
  createAiDocumentSchema,
  listAiConversationsQuerySchema,
  listAiDocumentsQuerySchema,
  updateAiDocumentSchema,
} from "./schemas/ai.schema.js";

export type {
  AiAssistModeValue,
  AiChatRequestInput,
  AiChatResponseDto,
  AiConfirmationDecisionResponseDto,
  AiConfirmationIdParamsInput,
  AiConfirmationRequiredDto,
  AiConversationDto,
  AiConversationIdParamsInput,
  AiDocumentDto,
  AiDocumentIdParamsInput,
  AiDocumentTypeValue,
  AiMessageDto,
  AiMessageRoleValue,
  CreateAiDocumentInput,
  ListAiConversationsQueryInput,
  ListAiDocumentsQueryInput,
  UpdateAiDocumentInput,
} from "./schemas/ai.schema.js";

// Schemas — Files
export {
  FILE_CATEGORIES,
  FILE_SHARE_ACCESS,
  FILE_SORT_FIELDS,
  createFolderSchema,
  fileActivityDtoSchema,
  fileCategorySchema,
  fileIdParamsSchema,
  fileShareAccessSchema,
  fileShareDtoSchema,
  fileVersionDtoSchema,
  folderDtoSchema,
  folderIdParamsSchema,
  listFilesQuerySchema,
  listFoldersQuerySchema,
  managedFileDtoSchema,
  moveFileSchema,
  shareFileSchema,
  shareIdParamsSchema,
  updateFileSchema,
  updateFolderSchema,
} from "./schemas/files.schema.js";

export type {
  CreateFolderInput,
  FileActivityDto,
  FileCategoryValue,
  FileIdParamsInput,
  FileShareAccessValue,
  FileShareDto,
  FileVersionDto,
  FolderDto,
  FolderIdParamsInput,
  ListFilesQueryInput,
  ListFoldersQueryInput,
  ManagedFileDto,
  MoveFileInput,
  ShareFileInput,
  ShareIdParamsInput,
  UpdateFileInput,
  UpdateFolderInput,
} from "./schemas/files.schema.js";

// Schemas — Calendar
export {
  CALENDAR_EVENT_CATEGORIES,
  CALENDAR_EVENT_STATUSES,
  CALENDAR_EVENT_TYPES,
  CALENDAR_VIEWS,
  EVENT_ATTENDEE_STATUSES,
  RECURRENCE_FREQUENCIES,
  REMINDER_CHANNELS,
  calendarEventCategorySchema,
  calendarEventDtoSchema,
  calendarEventIdParamsSchema,
  calendarEventStatusSchema,
  calendarEventTypeSchema,
  calendarViewSchema,
  createCalendarEventSchema,
  createHolidaySchema,
  eventAttendeeDtoSchema,
  eventAttendeeStatusSchema,
  eventReminderDtoSchema,
  holidayDtoSchema,
  holidayIdParamsSchema,
  listCalendarEventsQuerySchema,
  listHolidaysQuerySchema,
  moveCalendarEventSchema,
  recurrenceFrequencySchema,
  reminderChannelSchema,
  resizeCalendarEventSchema,
  respondInvitationSchema,
  updateCalendarEventSchema,
} from "./schemas/calendar.schema.js";

export type {
  CalendarEventCategoryValue,
  CalendarEventDto,
  CalendarEventIdParamsInput,
  CalendarEventStatusValue,
  CalendarEventTypeValue,
  CalendarViewValue,
  CreateCalendarEventInput,
  CreateHolidayInput,
  EventAttendeeDto,
  EventAttendeeStatusValue,
  EventReminderDto,
  HolidayDto,
  HolidayIdParamsInput,
  ListCalendarEventsQueryInput,
  ListHolidaysQueryInput,
  MoveCalendarEventInput,
  RecurrenceFrequencyValue,
  ReminderChannelValue,
  ResizeCalendarEventInput,
  RespondInvitationInput,
  UpdateCalendarEventInput,
} from "./schemas/calendar.schema.js";

// Schemas — Team
export {
  ADMIN_PERMISSION_PRESETS,
  ATTENDANCE_STATUSES,
  DOCUMENT_TYPES,
  EMPLOYEE_GENDERS,
  EMPLOYEE_STATUSES,
  EMPLOYMENT_TYPES,
  GOAL_STATUSES,
  LEAVE_REQUEST_STATUSES,
  LEAVE_TYPES,
  LEAVE_WORKFLOW_STATES,
  LIFECYCLE_STAGES,
  MARITAL_STATUSES,
  PERFORMANCE_RATINGS,
  PERFORMANCE_METRIC_KEYS,
  WORK_SHIFTS,
  adminPermissionPresetSchema,
  approveMonthlyReportSchema,
  assignDepartmentEmployeesSchema,
  attendanceDtoSchema,
  attendanceStatusSchema,
  checkInSchema,
  checkOutSchema,
  createAdminResultSchema,
  createAdminSchema,
  createDepartmentSchema,
  createEmployeeDocumentSchema,
  createEmployeeGoalSchema,
  createEmployeeProfileSchema,
  createLeaveRequestSchema,
  createPerformanceReviewSchema,
  createPromotionSchema,
  createTeamSchema,
  createTransferSchema,
  departmentDtoSchema,
  departmentIdParamsSchema,
  documentTypeSchema,
  employeeDocumentDtoSchema,
  employeeGenderSchema,
  employeeGoalDtoSchema,
  employeeIdCardDtoSchema,
  employeeIdParamsSchema,
  employeeProfileDtoSchema,
  employeePromotionDtoSchema,
  employeeStatusSchema,
  employeeTimelineEventDtoSchema,
  employeeTransferDtoSchema,
  employmentTypeSchema,
  goalIdParamsSchema,
  goalStatusSchema,
  hireEmployeeResultSchema,
  hireEmployeeSchema,
  leaveIdParamsSchema,
  leaveRequestDtoSchema,
  leaveRequestStatusSchema,
  leaveTypeSchema,
  leaveWorkflowStageDtoSchema,
  leaveWorkflowStateSchema,
  lifecycleStageSchema,
  listAttendanceQuerySchema,
  listEmployeesQuerySchema,
  listLeavesQuerySchema,
  maritalStatusSchema,
  performanceComponentScoreSchema,
  performanceDashboardDtoSchema,
  performanceEnabledMetricsSchema,
  performanceIdParamsSchema,
  performanceInsightDtoSchema,
  performanceMonthlyReportDtoSchema,
  performanceRatingSchema,
  performanceReviewDtoSchema,
  performanceScoreSnapshotDtoSchema,
  performanceScoringConfigDtoSchema,
  performanceWeightsSchema,
  recalculatePerformanceSchema,
  reviewLeaveSchema,
  resetEmployeeCredentialsResultSchema,
  resetEmployeeCredentialsSchema,
  teamDtoSchema,
  teamIdParamsSchema,
  teamMemberDtoSchema,
  teamMembersSchema,
  teamStatisticsDtoSchema,
  transferTeamMemberSchema,
  updateDepartmentSchema,
  updateEmployeeGoalSchema,
  updateEmployeeProfileSchema,
  updatePerformanceReviewSchema,
  updatePerformanceScoringConfigSchema,
  updateTeamSchema,
  workShiftSchema,
} from "./schemas/team.schema.js";

export type {
  AdminPermissionPresetValue,
  ApproveMonthlyReportInput,
  AssignDepartmentEmployeesInput,
  AttendanceDto,
  AttendanceStatusValue,
  CheckInInput,
  CheckOutInput,
  CreateAdminInput,
  CreateAdminResult,
  CreateDepartmentInput,
  CreateEmployeeDocumentInput,
  CreateEmployeeGoalInput,
  CreateEmployeeProfileInput,
  CreateLeaveRequestInput,
  CreatePerformanceReviewInput,
  CreatePromotionInput,
  CreateTeamInput,
  CreateTransferInput,
  DepartmentDto,
  DepartmentIdParamsInput,
  DocumentTypeValue,
  EmployeeDocumentDto,
  EmployeeGenderValue,
  EmployeeGoalDto,
  EmployeeIdCardDto,
  EmployeeIdParamsInput,
  EmployeeProfileDto,
  EmployeePublicDto,
  EmployeeSelfDto,
  EmployeeHrDto,
  EmployeePromotionDto,
  EmployeeStatusValue,
  EmployeeTimelineEventDto,
  EmployeeTransferDto,
  EmploymentTypeValue,
  GoalIdParamsInput,
  GoalStatusValue,
  HireEmployeeInput,
  HireEmployeeResult,
  LeaveIdParamsInput,
  LeaveRequestDto,
  LeaveRequestStatusValue,
  LeaveTypeValue,
  LeaveWorkflowStageDto,
  LeaveWorkflowStateValue,
  LifecycleStageValue,
  ListAttendanceQueryInput,
  ListEmployeesQueryInput,
  ListLeavesQueryInput,
  MaritalStatusValue,
  PerformanceComponentScore,
  PerformanceDashboardDto,
  PerformanceEnabledMetrics,
  PerformanceIdParamsInput,
  PerformanceInsightDto,
  PerformanceMetricKey,
  PerformanceMonthlyReportDto,
  PerformanceRatingValue,
  PerformanceReviewDto,
  PerformanceScoreSnapshotDto,
  PerformanceScoringConfigDto,
  PerformanceWeights,
  RecalculatePerformanceInput,
  ReviewLeaveInput,
  ResetEmployeeCredentialsInput,
  ResetEmployeeCredentialsResult,
  TeamDto,
  TeamIdParamsInput,
  TeamMemberDto,
  TeamMembersInput,
  TeamStatisticsDto,
  TransferTeamMemberInput,
  UpdateDepartmentInput,
  UpdateEmployeeGoalInput,
  UpdateEmployeeProfileInput,
  UpdatePerformanceReviewInput,
  UpdatePerformanceScoringConfigInput,
  UpdateTeamInput,
  WorkShiftValue,
} from "./schemas/team.schema.js";

// Schemas — Reports
export {
  REPORT_CATEGORIES,
  REPORT_DATE_RANGES,
  REPORT_EXPORT_FORMATS,
  REPORT_VISIBILITIES,
  analyticsDashboardDtoSchema,
  analyticsQuerySchema,
  aiInsightDtoSchema,
  chartPointSchema,
  createSavedReportSchema,
  exportReportSchema,
  kpiCardSchema,
  reportCategorySchema,
  reportDateRangeSchema,
  reportExportFormatSchema,
  reportFiltersSchema,
  reportTemplateDtoSchema,
  reportVisibilitySchema,
  savedReportDtoSchema,
  savedReportIdParamsSchema,
  updateSavedReportSchema,
} from "./schemas/reports.schema.js";

export type {
  AiInsightDto,
  AnalyticsDashboardDto,
  AnalyticsQueryInput,
  ChartPoint,
  CreateSavedReportInput,
  ExportReportInput,
  KpiCard,
  ReportCategoryValue,
  ReportDateRangeValue,
  ReportExportFormatValue,
  ReportFiltersInput,
  ReportTemplateDto,
  ReportVisibilityValue,
  SavedReportDto,
  SavedReportIdParamsInput,
  UpdateSavedReportInput,
} from "./schemas/reports.schema.js";

// Schemas — Notifications
export {
  NOTIFICATION_AUDIENCE_TYPES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_QUEUE_STATUSES,
  bulkNotificationIdsSchema,
  createNotificationSchema,
  listHistoryQuerySchema,
  listNotificationsQuerySchema,
  listQueueQuerySchema,
  notificationAudienceTypeSchema,
  notificationAuditDtoSchema,
  notificationCategorySchema,
  notificationChannelSchema,
  notificationDtoSchema,
  notificationIdParamsSchema,
  notificationPreferenceDtoSchema,
  notificationPrioritySchema,
  notificationQueueDtoSchema,
  notificationQueueStatusSchema,
  notificationTemplateDtoSchema,
  unreadCountDtoSchema,
  updatePreferenceSchema,
  updatePreferencesBatchSchema,
  notificationReplyDtoSchema,
  notificationReplyListResponseSchema,
  createNotificationReplySchema,
  notificationReplyIdParamsSchema,
} from "./schemas/notifications.schema.js";

export type {
  BulkNotificationIdsInput,
  CreateNotificationInput,
  ListHistoryQueryInput,
  ListNotificationsQueryInput,
  ListQueueQueryInput,
  NotificationAudienceTypeValue,
  NotificationAuditDto,
  NotificationCategoryValue,
  NotificationChannelValue,
  NotificationDto,
  NotificationIdParamsInput,
  NotificationPreferenceDto,
  NotificationPriorityValue,
  NotificationQueueDto,
  NotificationQueueStatusValue,
  NotificationTemplateDto,
  UnreadCountDto,
  UpdatePreferenceInput,
  UpdatePreferencesBatchInput,
  NotificationReplyDto,
  NotificationReplyListResponse,
  CreateNotificationReplyInput,
  NotificationReplyIdParamsInput,
} from "./schemas/notifications.schema.js";

// Types — Communication
export type {
  Activity,
  ActivityListResponse,
  Announcement,
  AnnouncementListResponse,
  Comment,
  CommentListResponse,
  CommunicationAiResponse,
  CommunicationPagination,
  CommunicationSearchResponse,
  Conversation,
  ConversationListResponse,
  DiscussionReply,
  DiscussionThread,
  DiscussionThreadListResponse,
  MeetingRoom,
  MeetingRoomListResponse,
  Message,
  MessageListResponse,
  UserPresence,
} from "./types/communication.types.js";

// Schemas — Communication
export {
  ACTIVITY_ENTITY_TYPES,
  COMMENT_ENTITY_TYPES,
  CONVERSATION_MEMBER_ROLES,
  CONVERSATION_TYPES,
  MESSAGE_KINDS,
  MESSAGE_READ_STATUSES,
  activityAttachmentDtoSchema,
  activityDtoSchema,
  activityEntityTypeSchema,
  addConversationMembersSchema,
  commentAttachmentDtoSchema,
  commentDtoSchema,
  commentEntityTypeSchema,
  commentIdParamsSchema,
  communicationSearchQuerySchema,
  communicationUserSummarySchema,
  conversationDtoSchema,
  conversationIdParamsSchema,
  conversationMemberDtoSchema,
  conversationMemberParamsSchema,
  conversationMemberRoleSchema,
  conversationTypeSchema,
  createCommentSchema,
  createConversationSchema,
  createMessageSchema,
  forwardMessageSchema,
  listActivitiesQuerySchema,
  listCommentsQuerySchema,
  listConversationsQuerySchema,
  listMessagesQuerySchema,
  markMessagesReadSchema,
  messageAttachmentDtoSchema,
  messageDtoSchema,
  messageIdParamsSchema,
  messageKindSchema,
  messageReactionDtoSchema,
  messageReadDtoSchema,
  messageReadStatusSchema,
  reactToMessageSchema,
  typingSchema,
  updateCommentSchema,
  updateConversationMemberSchema,
  updateConversationSchema,
  updateMessageSchema,
  userPresenceDtoSchema,
} from "./schemas/communication.schema.js";

export type {
  ActivityAttachmentDto,
  ActivityDto,
  ActivityEntityTypeValue,
  AddConversationMembersInput,
  AttachmentInput,
  CommentAttachmentDto,
  CommentDto,
  CommentEntityTypeValue,
  CommentIdParamsInput,
  CommunicationSearchQueryInput,
  ConversationDto,
  ConversationIdParamsInput,
  ConversationMemberDto,
  ConversationMemberParamsInput,
  ConversationMemberRoleValue,
  ConversationTypeValue,
  CreateCommentInput,
  CreateConversationInput,
  CreateMessageInput,
  ForwardMessageInput,
  ListActivitiesQueryInput,
  ListCommentsQueryInput,
  ListConversationsQueryInput,
  ListMessagesQueryInput,
  MarkMessagesReadInput,
  MessageAttachmentDto,
  MessageDto,
  MessageIdParamsInput,
  MessageKindValue,
  MessageReactionDto,
  MessageReadDto,
  MessageReadStatusValue,
  ReactToMessageInput,
  TypingInput,
  UpdateCommentInput,
  UpdateConversationInput,
  UpdateConversationMemberInput,
  UpdateMessageInput,
  UserPresenceDto,
} from "./schemas/communication.schema.js";

// Schemas — Communication Hub (Phase 20)
export {
  ANNOUNCEMENT_PRIORITIES,
  COMMUNICATION_AI_ACTIONS,
  DISCUSSION_THREAD_STATUSES,
  MEETING_PARTICIPANT_STATUSES,
  MEETING_STATUSES,
  announcementAttachmentDtoSchema,
  announcementDtoSchema,
  announcementIdParamsSchema,
  announcementPrioritySchema,
  communicationAiActionSchema,
  communicationAiRequestSchema,
  communicationAiResponseSchema,
  createAnnouncementSchema,
  createDiscussionReplySchema,
  createDiscussionThreadSchema,
  createMeetingRecordingSchema,
  createMeetingRoomSchema,
  createMeetingScreenShareSchema,
  discussionReplyDtoSchema,
  discussionThreadDtoSchema,
  discussionThreadStatusSchema,
  listAnnouncementsQuerySchema,
  listDiscussionThreadsQuerySchema,
  listMeetingsQuerySchema,
  meetingIdParamsSchema,
  meetingParticipantDtoSchema,
  meetingParticipantStatusSchema,
  meetingRecordingDtoSchema,
  meetingRoomDtoSchema,
  meetingScreenShareDtoSchema,
  meetingStatusSchema,
  replyIdParamsSchema,
  threadIdParamsSchema,
  updateAnnouncementSchema,
  updateDiscussionThreadSchema,
  updateMeetingParticipantSchema,
  updateMeetingRoomSchema,
} from "./schemas/communication-hub.schema.js";

export type {
  AnnouncementAttachmentDto,
  AnnouncementDto,
  AnnouncementIdParamsInput,
  AnnouncementPriorityValue,
  CommunicationAiActionValue,
  CommunicationAiRequestInput,
  CommunicationAiResponseDto,
  CreateAnnouncementInput,
  CreateDiscussionReplyInput,
  CreateDiscussionThreadInput,
  CreateMeetingRecordingInput,
  CreateMeetingRoomInput,
  CreateMeetingScreenShareInput,
  DiscussionReplyDto,
  DiscussionThreadDto,
  DiscussionThreadStatusValue,
  ListAnnouncementsQueryInput,
  ListDiscussionThreadsQueryInput,
  ListMeetingsQueryInput,
  MeetingIdParamsInput,
  MeetingParticipantDto,
  MeetingParticipantStatusValue,
  MeetingRecordingDto,
  MeetingRoomDto,
  MeetingScreenShareDto,
  MeetingStatusValue,
  ReplyIdParamsInput,
  ThreadIdParamsInput,
  UpdateAnnouncementInput,
  UpdateDiscussionThreadInput,
  UpdateMeetingParticipantInput,
  UpdateMeetingRoomInput,
} from "./schemas/communication-hub.schema.js";

// Types — Security
export type {
  ActiveDeviceDto,
  ActiveDeviceListResponse,
  AuditChainVerifyResponse,
  AuditExportResponse,
  ChangePasswordSecurityResponse,
  ContactFormResponse,
  CsrfTokenResponse,
  LoginHistoryDto,
  LoginHistoryListResponse,
  PasswordHistoryItemDto,
  PasswordHistoryListResponse,
  PasswordStatusDto,
  RetentionPoliciesResponse,
  RetentionPolicyDto,
  RetentionRunReportDto,
  RetentionStatusResponse,
  SecurityAuditLogDto,
  SecurityAuditLogListResponse,
  SecurityDashboardDto,
  SecurityEventDto,
  SecurityEventListResponse,
  SecurityIncidentDto,
  SecurityIncidentListResponse,
  SecurityPagination,
  SecurityScoreDto,
  ThreatMonitoringDashboard,
  UnlockAccountResponse,
  ZeroTrustPoliciesResponse,
  ZeroTrustStatusResponse,
  BcdrStatusResponse,
  BcdrServicesResponse,
  BcdrRecoveryTestResponse,
  BcdrRecoveryModeResponse,
  ComplianceStatusResponse,
  ComplianceFrameworksResponse,
  ComplianceControlsResponse,
  ComplianceAssessmentResponse,
  SiemStatusResponse,
  SiemConfigResponse,
  SiemTestResponse,
  SiemExportResponse,
  SiemRetryResponse,
  SiemIntegrationDashboard,
  BackupValidationStatusResponse,
  BackupValidationReportResponse,
  BackupValidationHistoryResponse,
  BackupValidationDashboard,
  EncryptionAuditStatusResponse,
  EncryptionAuditReportResponse,
  EncryptionAuditHistoryResponse,
  EncryptionAuditDashboard,
  DisasterRecoveryTestStatusResponse,
  DisasterRecoveryTestReportResponse,
  DisasterRecoveryTestHistoryResponse,
  DisasterRecoveryTestDashboard,
  PenetrationTestStatusResponse,
  PenetrationTestReportResponse,
  PenetrationTestHistoryResponse,
  PenetrationTestDashboard,
} from "./types/security.types.js";

// Schemas — Security
export {
  SECURITY_EVENT_CATEGORIES,
  SECURITY_SEVERITIES,
  activeDeviceDtoSchema,
  auditChainVerifyResponseSchema,
  auditExportItemSchema,
  auditExportResponseSchema,
  auditVerificationStatusSchema,
  captchaTokenSchema,
  contactFormSchema,
  listActiveSessionsQuerySchema,
  listLoginHistoryQuerySchema,
  listSecurityEventsQuerySchema,
  listSecurityIncidentsQuerySchema,
  listSecurityLogsQuerySchema,
  loginHistoryDtoSchema,
  passwordHistoryItemDtoSchema,
  passwordStatusDtoSchema,
  resolveSecurityEventParamsSchema,
  resolveSecurityIncidentParamsSchema,
  retentionEntityTypeSchema,
  retentionLifecycleStatusSchema,
  retentionPoliciesResponseSchema,
  retentionPolicyDtoSchema,
  retentionRunReportSchema,
  retentionStatusResponseSchema,
  securityAuditLogDtoSchema,
  securityDashboardDtoSchema,
  securityEventCategorySchema,
  securityEventDtoSchema,
  securityIncidentDtoSchema,
  securityIncidentStatusSchema,
  securityScoreDtoSchema,
  securitySeveritySchema,
  terminateSessionParamsSchema,
  threatMonitoringDashboardSchema,
  unlockAccountSchema,
  zeroTrustDecisionSchema,
  zeroTrustPoliciesResponseSchema,
  zeroTrustPolicyDtoSchema,
  zeroTrustRiskLevelSchema,
  zeroTrustStatusResponseSchema,
  bcdrHealthStatusSchema,
  bcdrRecoveryModeSchema,
  bcdrServiceIdSchema,
  bcdrServiceHealthSchema,
  bcdrServicesResponseSchema,
  bcdrStatusResponseSchema,
  bcdrRecoveryTestResponseSchema,
  setBcdrRecoveryModeSchema,
  bcdrRecoveryModeResponseSchema,
  complianceFrameworkSchema,
  complianceControlStatusSchema,
  complianceRiskLevelSchema,
  complianceEvidenceItemSchema,
  complianceControlDtoSchema,
  complianceFrameworkScoreSchema,
  complianceRiskSummarySchema,
  complianceStatusResponseSchema,
  complianceFrameworksResponseSchema,
  complianceControlsQuerySchema,
  complianceControlsResponseSchema,
  complianceAssessmentResponseSchema,
  siemProviderSchema,
  siemConnectionStatusSchema,
  siemDeliveryResultSchema,
  siemStatusResponseSchema,
  siemConfigResponseSchema,
  siemTestResponseSchema,
  siemExportQuerySchema,
  siemExportResponseSchema,
  siemRetryQuerySchema,
  siemRetryResponseSchema,
  siemIntegrationDashboardSchema,
  backupHealthStatusSchema,
  backupValidationTypeSchema,
  backupValidationStatusResponseSchema,
  backupCheckResultSchema,
  backupCategoryValidationSchema,
  backupValidationReportResponseSchema,
  runBackupValidationSchema,
  backupValidationHistoryQuerySchema,
  backupValidationHistoryResponseSchema,
  backupValidationDashboardSchema,
  encryptionAuditStatusEnumSchema,
  encryptionAuditStatusResponseSchema,
  encryptionAuditCheckResultSchema,
  encryptionAuditRecommendationSchema,
  encryptionAuditSourceResultSchema,
  encryptionAuditReportResponseSchema,
  encryptionAuditHistoryQuerySchema,
  encryptionAuditHistoryResponseSchema,
  encryptionAuditDashboardSchema,
  drTestStatusSchema,
  drTestTypeSchema,
  disasterRecoveryTestStatusResponseSchema,
  disasterRecoveryTestCategorySchema,
  disasterRecoveryTestReportResponseSchema,
  runDisasterRecoveryTestSchema,
  disasterRecoveryTestHistoryQuerySchema,
  disasterRecoveryTestHistoryResponseSchema,
  disasterRecoveryTestDashboardSchema,
  pentestSeveritySchema,
  pentestTypeSchema,
  securityMaturitySchema,
  penetrationTestStatusResponseSchema,
  pentestFindingSchema,
  penetrationTestReportResponseSchema,
  runPenetrationTestSchema,
  penetrationTestHistoryQuerySchema,
  penetrationTestHistoryResponseSchema,
  penetrationTestDashboardSchema,
  deviceStateSchema,
  deviceTypeSchema,
  managedDeviceDtoSchema,
  managedDeviceListResponseSchema,
  deviceIdParamsSchema,
  deviceUserParamsSchema,
  trustDeviceSchema,
  renameDeviceSchema,
  deviceActionSchema,
  listManagedDevicesQuerySchema,
  deviceManagementDashboardSchema,
  tenantIsolationSeveritySchema,
  tenantIsolationControlStatusSchema,
  tenantIsolationCategorySchema,
  tenantIsolationStatusResponseSchema,
  tenantIsolationFindingSchema,
  tenantIsolationReportResponseSchema,
  runTenantIsolationSchema,
  tenantIsolationHistoryQuerySchema,
  tenantIsolationHistoryResponseSchema,
  tenantIsolationDashboardSchema,
  securityRegressionSeveritySchema,
  securityRegressionControlStatusSchema,
  securityRegressionCategorySchema,
  securityRegressionTestTypeSchema,
  securityRegressionStatusResponseSchema,
  securityRegressionFindingSchema,
  securityRegressionReportResponseSchema,
  runSecurityRegressionSchema,
  securityRegressionHistoryQuerySchema,
  securityRegressionHistoryResponseSchema,
  securityRegressionDashboardSchema,
  apiVersionStatusEnumSchema,
  apiVersioningStatusResponseSchema,
  apiVersioningVersionsResponseSchema,
  apiVersioningCompatibilityResponseSchema,
  apiVersioningDashboardSchema,
  webhookDeliveryStatusSchema,
  webhookFailureClassSchema,
  webhookDeliveryDtoSchema,
  webhookSecurityStatusResponseSchema,
  webhookSecurityDeliveriesResponseSchema,
  webhookSecurityRetriesResponseSchema,
  webhookRotateSecretResponseSchema,
  webhookRetryDeliveryParamsSchema,
  webhookSecurityRetryResponseSchema,
  webhookSecurityDashboardSchema,
} from "./schemas/security.schema.js";

export type {
  AuditExportItem,
  AuditVerificationStatus,
  ContactFormInput,
  ListActiveSessionsQueryInput,
  ListLoginHistoryQueryInput,
  ListSecurityEventsQueryInput,
  ListSecurityIncidentsQueryInput,
  ListSecurityLogsQueryInput,
  ResolveSecurityEventParamsInput,
  ResolveSecurityIncidentParamsInput,
  TerminateSessionParamsInput,
  UnlockAccountInput,
  SetBcdrRecoveryModeInput,
  ComplianceControlsQueryInput,
  SiemExportQueryInput,
  SiemRetryQueryInput,
  RunBackupValidationInput,
  BackupValidationHistoryQueryInput,
  EncryptionAuditHistoryQueryInput,
  RunDisasterRecoveryTestInput,
  DisasterRecoveryTestHistoryQueryInput,
  RunPenetrationTestInput,
  PenetrationTestHistoryQueryInput,
  DeviceIdParamsInput,
  DeviceUserParamsInput,
  TrustDeviceInput,
  RenameDeviceInput,
  DeviceActionInput,
  ListManagedDevicesQueryInput,
  ManagedDeviceDto,
  ManagedDeviceListResponse,
  DeviceManagementDashboard,
  TenantIsolationStatusResponse,
  TenantIsolationReportResponse,
  RunTenantIsolationInput,
  TenantIsolationHistoryQueryInput,
  TenantIsolationHistoryResponse,
  TenantIsolationDashboard,
  SecurityRegressionStatusResponse,
  SecurityRegressionReportResponse,
  RunSecurityRegressionInput,
  SecurityRegressionHistoryQueryInput,
  SecurityRegressionHistoryResponse,
  SecurityRegressionDashboard,
  ApiVersioningStatusResponse,
  ApiVersioningVersionsResponse,
  ApiVersioningCompatibilityResponse,
  ApiVersioningDashboard,
  WebhookSecurityStatusResponse,
  WebhookSecurityDeliveriesResponse,
  WebhookSecurityRetriesResponse,
  WebhookRotateSecretResponse,
  WebhookRetryDeliveryParamsInput,
  WebhookSecurityRetryResponse,
  WebhookSecurityDashboard,
} from "./schemas/security.schema.js";

// Types — Settings
export type {
  AiSettingsDto,
  AppearanceSettingsDto,
  AppLanguageCode,
  BackupRecordDto,
  BillingSettingsDto,
  CompanySettingsDto,
  IntegrationCredentialDto,
  LocaleSettingsDto,
  NotificationSettingsDto,
  SecurityPreferencesDto,
  SettingsOverviewDto,
  SettingsProfileDto,
  StorageSettingsDto,
  UpdateAiSettingsInput,
  UpdateAppearanceSettingsInput,
  UpdateCompanySettingsInput,
  UpdateLocaleSettingsInput,
  UpdateNotificationSettingsInput,
  UpdateSecurityPreferencesInput,
  UpdateSettingsProfileInput,
} from "./types/settings.types.js";

// Schemas — Settings
export {
  APP_LANGUAGES,
  BORDER_RADII,
  DASHBOARD_DENSITIES,
  FONT_SIZES,
  INTEGRATION_PROVIDERS,
  SIDEBAR_STYLES,
  THEME_MODES,
  appLanguageSchema,
  backupIdParamsSchema,
  borderRadiusSchema,
  createBackupSchema,
  createIntegrationCredentialSchema,
  dashboardDensitySchema,
  fontSizeSchema,
  integrationCredentialIdParamsSchema,
  integrationProviderSchema,
  requestAccountDeletionSchema,
  settingsProfileDtoSchema,
  sidebarStyleSchema,
  themeModeSchema,
  PROFILE_DOCUMENT_TYPES,
  profileDocumentDtoSchema,
  profileDocumentIdParamsSchema,
  profileDocumentTypeSchema,
  createProfileDocumentMetaSchema,
  updateAiSettingsSchema,
  updateAppearanceSettingsSchema,
  updateBillingSettingsSchema,
  updateCompanySettingsSchema,
  updateIntegrationCredentialSchema,
  updateLocaleSettingsSchema,
  updateNotificationSettingsSchema,
  updateSecurityPreferencesSchema,
  updateSettingsProfileSchema,
} from "./schemas/settings.schema.js";

export type {
  BackupIdParamsInput,
  CreateBackupInput,
  CreateIntegrationCredentialInput,
  CreateProfileDocumentMetaInput,
  IntegrationCredentialIdParamsInput,
  ProfileDocumentDto,
  ProfileDocumentIdParamsInput,
  ProfileDocumentType,
  RequestAccountDeletionInput,
  UpdateBillingSettingsInput,
  UpdateIntegrationCredentialInput,
} from "./schemas/settings.schema.js";

export {
  GLOBAL_SEARCH_SCOPES,
  globalSearchHitSchema,
  globalSearchQuerySchema,
  globalSearchResponseSchema,
  globalSearchScopeSchema,
} from "./schemas/search.schema.js";

export type {
  GlobalSearchHit,
  GlobalSearchQueryInput,
  GlobalSearchResponse,
  GlobalSearchScope,
} from "./schemas/search.schema.js";

// Types — Integrations (Phase 19.1)
export type {
  IntegrationConnectResponse,
  IntegrationDetailDto,
  IntegrationDisconnectResponse,
  IntegrationDto,
  IntegrationLogDto,
  IntegrationLogListResponse,
  IntegrationLogLevelValue,
  IntegrationOverviewDto,
  IntegrationConnectionStatusValue,
  IntegrationHealthStatusValue,
  IntegrationSyncStatusValue,
  IntegrationTestResponse,
  IntegrationApiUsageDto,
  IntegrationHealthTimelinePoint,
  SyncHistoryDto,
  SyncHistoryListResponse,
  WebhookEndpointDto,
} from "./types/integrations.types.js";

export type {
  IntegrationOAuthConnectResponse,
  IntegrationOverviewKpis,
  IntegrationProviderStatusDto,
  OAuthIntegrationProvider,
  ApiKeyIntegrationProvider,
  IntegrationProviderRoute,
} from "./types/integrations-oauth.types.js";

export type {
  IntegrationLiveMonitoringDto,
  IntegrationMonitoringOverviewDto,
  SyncQueueJobDto,
  SyncQueueOverviewDto,
  SyncSchedulerConfigDto,
  SyncSchedulerPresetValue,
  WebhookMonitorOverviewDto,
  IntegrationUsageAnalyticsDto,
  IntegrationAlertDto,
  IntegrationAlertListResponse,
  IntegrationAlertTypeValue,
  IntegrationAlertSeverityValue,
  IntegrationPlatformDetailDto,
} from "./types/integrations-monitoring.types.js";

// Schemas — Integrations (Phase 19.1 / 19.2)
export {
  INTEGRATION_CONNECTION_STATUSES,
  INTEGRATION_HEALTH_STATUSES,
  INTEGRATION_LOG_LEVELS,
  INTEGRATION_SLUGS,
  INTEGRATION_SYNC_STATUSES,
  OAUTH_INTEGRATION_PROVIDERS,
  API_KEY_INTEGRATION_PROVIDERS,
  AI_PROVIDER_IDS,
  SYNC_SCHEDULER_PRESETS,
  INTEGRATION_ALERT_TYPES,
  INTEGRATION_ALERT_SEVERITIES,
  connectIntegrationSchema,
  connectApiKeyIntegrationSchema,
  disconnectIntegrationSchema,
  integrationConnectionStatusSchema,
  integrationHealthStatusSchema,
  integrationIdParamsSchema,
  integrationSlugParamsSchema,
  integrationLogLevelSchema,
  integrationSlugSchema,
  integrationSyncStatusSchema,
  listIntegrationLogsQuerySchema,
  listIntegrationsQuerySchema,
  listSyncHistoryQuerySchema,
  listIntegrationAlertsQuerySchema,
  oauthCallbackQuerySchema,
  oauthIntegrationProviderSchema,
  oauthProviderParamsSchema,
  apiKeyIntegrationProviderSchema,
  apiKeyProviderParamsSchema,
  aiProviderIdSchema,
  syncSchedulerPresetSchema,
  integrationAlertTypeSchema,
  integrationAlertSeveritySchema,
  updateSchedulerConfigSchema,
  syncJobIdParamsSchema,
  acknowledgeAlertSchema,
  manualSyncSchema,
  testIntegrationSchema,
} from "./schemas/integrations.schema.js";

export type {
  ConnectIntegrationInput,
  ConnectApiKeyIntegrationInput,
  DisconnectIntegrationInput,
  IntegrationIdParamsInput,
  IntegrationSlugParamsInput,
  ListIntegrationLogsQueryInput,
  ListIntegrationsQueryInput,
  ListSyncHistoryQueryInput,
  ListIntegrationAlertsQueryInput,
  OAuthCallbackQueryInput,
  OAuthIntegrationProviderValue,
  OAuthProviderParamsInput,
  ApiKeyIntegrationProviderValue,
  ApiKeyProviderParamsInput,
  AiProviderIdValue,
  UpdateSchedulerConfigInput,
  SyncJobIdParamsInput,
  AcknowledgeAlertInput,
  ManualSyncInput,
  TestIntegrationInput,
} from "./schemas/integrations.schema.js";

// Schemas — Whiteboards
export {
  WHITEBOARD_AI_ACTIONS,
  WHITEBOARD_EXPORT_FORMATS,
  createWhiteboardCommentSchema,
  createWhiteboardSchema,
  duplicateWhiteboardSchema,
  listWhiteboardsQuerySchema,
  renameWhiteboardSchema,
  updateWhiteboardSchema,
  whiteboardAiActionSchema,
  whiteboardAiRequestSchema,
  whiteboardCanvasDataSchema,
  whiteboardCommentDtoSchema,
  whiteboardDtoSchema,
  whiteboardExportFormatSchema,
  whiteboardIdParamsSchema,
  whiteboardListItemSchema,
  whiteboardListResponseSchema,
  whiteboardVersionDtoSchema,
} from "./schemas/whiteboard.schema.js";

export type {
  CreateWhiteboardCommentInput,
  CreateWhiteboardInput,
  DuplicateWhiteboardInput,
  ListWhiteboardsQueryInput,
  RenameWhiteboardInput,
  UpdateWhiteboardInput,
  WhiteboardAiActionValue,
  WhiteboardAiRequestInput,
  WhiteboardCanvasDataInput,
  WhiteboardCommentDto,
  WhiteboardDto,
  WhiteboardExportFormatValue,
  WhiteboardIdParamsInput,
  WhiteboardListItem,
  WhiteboardListResponse,
  WhiteboardVersionDto,
} from "./schemas/whiteboard.schema.js";

// Schemas / types — Subscription & Billing
export {
  SUBSCRIPTION_PLAN_INTERVALS,
  cancelSubscriptionSchema,
  checkoutSessionResponseSchema,
  createCheckoutSessionSchema,
  organizationSubscriptionDtoSchema,
  subscriptionEventDtoSchema,
  subscriptionPlanDtoSchema,
} from "./schemas/billing.schema.js";

export type {
  CancelSubscriptionInput,
  CheckoutSessionResponse,
  CreateCheckoutSessionInput,
  OrganizationSubscriptionDto,
  SubscriptionEventDto,
  SubscriptionPlanDto,
} from "./types/billing.types.js";

// Public API v1
export {
  PUBLIC_API_ERROR_CODES,
  PUBLIC_API_KEY_PREFIX,
  PUBLIC_API_SCOPES,
  PUBLIC_API_SCOPE_VALUES,
} from "./constants/public-api.constants.js";

export type {
  PublicApiErrorCode,
  PublicApiScope,
} from "./constants/public-api.constants.js";

export {
  createPublicApiKeySchema,
  publicApiIdParamsSchema,
  publicApiKeyDtoSchema,
  publicApiKeyIdParamsSchema,
  publicApiListQuerySchema,
} from "./schemas/public-api.schema.js";

export type {
  CreatePublicApiKeyInput,
  PublicApiIdParamsInput,
  PublicApiKeyDto,
  PublicApiKeyIdParamsInput,
  PublicApiListQueryInput,
} from "./schemas/public-api.schema.js";

// Schemas — Customer Requests (Phase 1 intake + Phase 2 continuation)
export {
  CUSTOMER_REQUEST_CONTINUATION_TYPES,
  CUSTOMER_REQUEST_INTAKE_TYPES,
  CUSTOMER_REQUEST_KINDS,
  CUSTOMER_REQUEST_PRIORITIES,
  CUSTOMER_REQUEST_SORT_FIELDS,
  CUSTOMER_REQUEST_STATUSES,
  CUSTOMER_REQUEST_TYPES,
  REOPEN_ELIGIBLE_PROJECT_STATUSES,
  addCustomerRequestAttachmentSchema,
  approveCustomerRequestSchema,
  clarifyCustomerRequestSchema,
  convertCustomerRequestSchema,
  createCustomerRequestSchema,
  customerRequestAttachmentSchema,
  customerRequestContinuationTypeSchema,
  customerRequestIdParamsSchema,
  customerRequestIntakeTypeSchema,
  customerRequestKindSchema,
  customerRequestPrioritySchema,
  customerRequestSchema,
  customerRequestStatusSchema,
  customerRequestTypeSchema,
  isCustomerRequestContinuationType,
  isCustomerRequestIntakeType,
  listCustomerRequestsQuerySchema,
  rejectCustomerRequestSchema,
  startCustomerRequestReviewSchema,
  updateCustomerRequestSchema,
} from "./schemas/customer-requests.schema.js";

export type {
  AddCustomerRequestAttachmentInput,
  ApproveCustomerRequestInput,
  ClarifyCustomerRequestInput,
  ConvertCustomerRequestInput,
  CreateCustomerRequestInput,
  CustomerRequestAttachmentDto,
  CustomerRequestContinuationTypeValue,
  CustomerRequestDto,
  CustomerRequestIdParamsInput,
  CustomerRequestIntakeTypeValue,
  CustomerRequestKindValue,
  CustomerRequestPriorityValue,
  CustomerRequestStatusValue,
  CustomerRequestTypeValue,
  ListCustomerRequestsQueryInput,
  RejectCustomerRequestInput,
  StartCustomerRequestReviewInput,
  UpdateCustomerRequestInput,
} from "./schemas/customer-requests.schema.js";

// Schemas — Quotes (Phase 3 commercial foundation)
export {
  PAYMENT_MODELS,
  PAYMENT_SCHEDULE_KINDS,
  QUOTE_SORT_FIELDS,
  QUOTE_STATUSES,
  calculateQuoteTotals,
  createQuoteSchema,
  generateQuoteInvoicesSchema,
  listQuotesQuerySchema,
  paymentModelSchema,
  paymentScheduleInputSchema,
  paymentScheduleItemSchema,
  paymentScheduleKindSchema,
  quoteIdParamsSchema,
  quoteItemSchema,
  quoteSchema,
  quoteStatusSchema,
  rejectQuoteSchema,
  updateQuoteSchema,
} from "./schemas/quotes.schema.js";

export type {
  CreateQuoteInput,
  GenerateQuoteInvoicesInput,
  ListQuotesQueryInput,
  PaymentModelValue,
  PaymentScheduleInput,
  PaymentScheduleItemDto,
  PaymentScheduleKindValue,
  QuoteDto,
  QuoteIdParamsInput,
  QuoteItemDto,
  QuoteStatusValue,
  RejectQuoteInput,
  UpdateQuoteInput,
} from "./schemas/quotes.schema.js";

export {
  PAYMENT_MODEL_LABELS,
  PAYMENT_SCHEDULE_KIND_LABELS,
  calculatePaymentSchedule,
} from "./utils/payment-schedule.js";

export type { CalculatedScheduleItem } from "./utils/payment-schedule.js";
