/** Phase 17 — Enterprise Security module constants */

export const SECURITY_AUDIT_RESOURCE = "security" as const;

export const SECURITY_AUDIT_ACTIONS = {
  PASSWORD_CHANGED: "security.password_changed",
  PASSWORD_REUSE_BLOCKED: "security.password_reuse_blocked",
  PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",
  PASSWORD_CHANGE_COMPLETED: "PASSWORD_CHANGE_COMPLETED",
  PASSWORD_CHANGE_BLOCKED: "PASSWORD_CHANGE_BLOCKED",
  PASSWORD_EXPIRED: "PASSWORD_EXPIRED",
  PASSWORD_HISTORY_REJECTED: "PASSWORD_HISTORY_REJECTED",
  PASSWORD_POLICY_UPDATED: "PASSWORD_POLICY_UPDATED",
  ACCOUNT_UNLOCKED: "security.account_unlocked",
  SESSION_TERMINATED: "security.session_terminated",
  CONTACT_SUBMITTED: "security.contact_submitted",
  CAPTCHA_FAILED: "security.captcha_failed",
  CSRF_REJECTED: "security.csrf_rejected",
  ALERT_RESOLVED: "security.alert_resolved",
  DASHBOARD_VIEWED: "security.dashboard_viewed",
  AUDIT_CHAIN_VERIFIED: "security.audit_chain_verified",
  AUDIT_EXPORTED: "security.audit_exported",
  RETENTION_RUN: "security.retention_run",
  INCIDENT_RESOLVED: "security.incident_resolved",
  ZERO_TRUST_STATUS: "security.zero_trust_status_viewed",
  BCDR_STATUS: "security.bcdr_status_viewed",
  BCDR_SERVICES: "security.bcdr_services_viewed",
  BCDR_TEST: "security.bcdr_recovery_test",
  BCDR_RECOVERY_MODE: "security.bcdr_recovery_mode_set",
  COMPLIANCE_STATUS: "security.compliance_status_viewed",
  COMPLIANCE_FRAMEWORKS: "security.compliance_frameworks_viewed",
  COMPLIANCE_CONTROLS: "security.compliance_controls_viewed",
  COMPLIANCE_ASSESSMENT: "security.compliance_assessment_run",
  SIEM_STATUS: "security.siem_status_viewed",
  SIEM_CONFIG: "security.siem_config_viewed",
  SIEM_TEST: "security.siem_connectivity_test",
  SIEM_EXPORT: "security.siem_export",
  SIEM_RETRY: "security.siem_retry",
  BACKUP_VALIDATION_STATUS: "security.backup_validation_status_viewed",
  BACKUP_VALIDATION_REPORT: "security.backup_validation_report_viewed",
  BACKUP_VALIDATION_RUN: "security.backup_validation_run",
  BACKUP_VALIDATION_HISTORY: "security.backup_validation_history_viewed",
  ENCRYPTION_AUDIT_STATUS: "security.encryption_audit_status_viewed",
  ENCRYPTION_AUDIT_REPORT: "security.encryption_audit_report_viewed",
  ENCRYPTION_AUDIT_RUN: "security.encryption_audit_run",
  ENCRYPTION_AUDIT_HISTORY: "security.encryption_audit_history_viewed",
  DR_TEST_STATUS: "security.disaster_recovery_test_status_viewed",
  DR_TEST_HISTORY: "security.disaster_recovery_test_history_viewed",
  DR_TEST_RUN: "security.disaster_recovery_test_run",
  DR_TEST_REPORT: "security.disaster_recovery_test_report_viewed",
  PENTEST_STATUS: "security.pentest_status_viewed",
  PENTEST_REPORT: "security.pentest_report_viewed",
  PENTEST_RUN: "security.pentest_run",
  PENTEST_HISTORY: "security.pentest_history_viewed",
  TENANT_ISOLATION_STATUS: "security.tenant_isolation_status_viewed",
  TENANT_ISOLATION_REPORT: "security.tenant_isolation_report_viewed",
  TENANT_ISOLATION_RUN: "security.tenant_isolation_run",
  TENANT_ISOLATION_HISTORY: "security.tenant_isolation_history_viewed",
  SECURITY_REGRESSION_STATUS: "security.regression_status_viewed",
  SECURITY_REGRESSION_REPORT: "security.regression_report_viewed",
  SECURITY_REGRESSION_RUN: "security.regression_run",
  SECURITY_REGRESSION_HISTORY: "security.regression_history_viewed",
  API_VERSIONING_STATUS: "security.api_versioning_status_viewed",
  API_VERSIONING_VERSIONS: "security.api_versioning_versions_viewed",
  API_VERSIONING_COMPATIBILITY: "security.api_versioning_compatibility_viewed",
  WEBHOOK_SECURITY_STATUS: "security.webhook_security_status_viewed",
  WEBHOOK_SECURITY_DELIVERIES: "security.webhook_security_deliveries_viewed",
  WEBHOOK_SECURITY_RETRIES: "security.webhook_security_retries_viewed",
  WEBHOOK_SECURITY_ROTATE: "security.webhook_security_secret_rotated",
  WEBHOOK_SECURITY_RETRY: "security.webhook_security_retry_requested",
} as const;

export const SECURITY_EVENT_TYPES = {
  ACCOUNT_LOCKED: "account_locked",
  ACCOUNT_UNLOCKED: "account_unlocked",
  FAILED_LOGIN_BURST: "failed_login_burst",
  PASSWORD_REUSE: "password_reuse",
  TOKEN_REUSE: "token_reuse",
  CAPTCHA_FAILED: "captcha_failed",
  RATE_LIMITED: "rate_limited",
  SESSION_TERMINATED: "session_terminated",
  SUSPICIOUS_LOGIN: "suspicious_login",
  AUDIT_CHAIN_CORRUPTED: "AUDIT_CHAIN_CORRUPTED",
} as const;

export const SECURITY_MESSAGES = {
  PASSWORD_CHANGED: "Password updated successfully.",
  PASSWORD_REUSED:
    "This password was used recently. Please choose a different password.",
  ACCOUNT_UNLOCKED: "Account unlocked successfully.",
  SESSION_TERMINATED: "Session terminated successfully.",
  CONTACT_RECEIVED:
    "Thank you. Your message has been received and will be reviewed shortly.",
  CAPTCHA_FAILED: "Captcha verification failed. Please try again.",
  CSRF_INVALID: "Invalid or missing CSRF token.",
  ALERT_RESOLVED: "Security alert marked as resolved.",
  NOT_FOUND: "Resource not found",
  FORBIDDEN: "You do not have permission to perform this action",
  AUDIT_CHAIN_VERIFIED: "Audit integrity chain verified.",
  AUDIT_CHAIN_INVALID: "Audit integrity verification completed.",
  AUDIT_EXPORT_READY: "Audit export ready.",
  RETENTION_POLICIES: "Retention policies retrieved.",
  RETENTION_STATUS: "Retention status retrieved.",
  RETENTION_RUN: "Retention processor completed.",
  INCIDENT_RESOLVED: "Security incident resolved.",
  ZERO_TRUST_STATUS: "Zero Trust status retrieved.",
  ZERO_TRUST_POLICIES: "Zero Trust policies retrieved.",
  BCDR_STATUS: "Business continuity status retrieved.",
  BCDR_SERVICES: "Business continuity services retrieved.",
  BCDR_TEST: "Business continuity recovery test completed.",
  BCDR_RECOVERY_MODE: "Business continuity recovery mode updated.",
  COMPLIANCE_STATUS: "Compliance status retrieved.",
  COMPLIANCE_FRAMEWORKS: "Compliance frameworks retrieved.",
  COMPLIANCE_CONTROLS: "Compliance controls retrieved.",
  COMPLIANCE_ASSESSMENT: "Compliance assessment completed.",
  SIEM_STATUS: "SIEM status retrieved.",
  SIEM_CONFIG: "SIEM configuration retrieved.",
  SIEM_TEST: "SIEM connectivity test completed.",
  SIEM_EXPORT: "SIEM export ready.",
  SIEM_RETRY: "SIEM dead-letter retry completed.",
  BACKUP_VALIDATION_STATUS: "Backup validation status retrieved.",
  BACKUP_VALIDATION_REPORT: "Backup validation report retrieved.",
  BACKUP_VALIDATION_RUN: "Backup validation completed.",
  BACKUP_VALIDATION_HISTORY: "Backup validation history retrieved.",
  ENCRYPTION_AUDIT_STATUS: "Encryption audit status retrieved.",
  ENCRYPTION_AUDIT_REPORT: "Encryption audit report retrieved.",
  ENCRYPTION_AUDIT_RUN: "Encryption audit completed.",
  ENCRYPTION_AUDIT_HISTORY: "Encryption audit history retrieved.",
  DR_TEST_STATUS: "Disaster recovery test status retrieved.",
  DR_TEST_HISTORY: "Disaster recovery test history retrieved.",
  DR_TEST_RUN: "Disaster recovery test completed.",
  DR_TEST_REPORT: "Disaster recovery test report retrieved.",
  PENTEST_STATUS: "Penetration test status retrieved.",
  PENTEST_REPORT: "Penetration test report retrieved.",
  PENTEST_RUN: "Penetration test assessment completed.",
  PENTEST_HISTORY: "Penetration test history retrieved.",
  TENANT_ISOLATION_STATUS: "Tenant isolation status retrieved.",
  TENANT_ISOLATION_REPORT: "Tenant isolation report retrieved.",
  TENANT_ISOLATION_RUN: "Tenant isolation assessment completed.",
  TENANT_ISOLATION_HISTORY: "Tenant isolation history retrieved.",
  SECURITY_REGRESSION_STATUS: "Security regression status retrieved.",
  SECURITY_REGRESSION_REPORT: "Security regression report retrieved.",
  SECURITY_REGRESSION_RUN: "Security regression assessment completed.",
  SECURITY_REGRESSION_HISTORY: "Security regression history retrieved.",
  API_VERSIONING_STATUS: "API versioning status retrieved.",
  API_VERSIONING_VERSIONS: "API versions retrieved.",
  API_VERSIONING_COMPATIBILITY: "API version compatibility retrieved.",
  WEBHOOK_SECURITY_STATUS: "Webhook security status retrieved.",
  WEBHOOK_SECURITY_DELIVERIES: "Webhook deliveries retrieved.",
  WEBHOOK_SECURITY_RETRIES: "Webhook retries retrieved.",
  WEBHOOK_SECURITY_ROTATE: "Webhook signing secret rotated.",
  WEBHOOK_SECURITY_RETRY: "Webhook delivery retry requested.",
} as const;
